[labels]
app.name = Hulp
errors.not_logged_in = Nie aangemeld nie
errors.invalid_kind = Ongeldige tipe
errors.help_not_configured = Hulp is nie vir hierdie bediener gekonfigureer nie
errors.body_is_required = Tik asseblief iets voordat jy indien
errors.title_is_required = Gee asseblief jou plasing 'n titel
errors.no_fingerprint_returned = Die bestemming het geen vingerafdruk teruggestuur nie
titles.intro = Stel {name} bekend
titles.question = 'n Vraag van {name}
errors.body_too_long = Jou boodskap is te lank
errors.title_too_long = Jou titel is te lank
titles.someone = Iemand
