[labels]
app.name = እገዛ
errors.not_logged_in = አልገቡም
errors.invalid_kind = ልክ ያልሆነ ዓይነት
errors.help_not_configured = ለዚህ አገልጋይ እርዳታ አልተዋቀረም
errors.body_is_required = እባክዎ ከማስገባትዎ በፊት የሆነ ነገር ይተይቡ
errors.title_is_required = እባክዎ ለልጥፍዎ ርዕስ ይስጡ
errors.no_fingerprint_returned = መድረሻው የጣት አሻራ አልመለሰም
titles.intro = {name}ን በማስተዋወቅ ላይ
errors.body_too_long = መልእክትዎ በጣም ረጅም ነው
errors.title_too_long = ርዕስዎ በጣም ረጅም ነው
titles.someone = አንድ ሰው
