[labels]
app.name = Yanapt'a
errors.not_logged_in = Janiw mantkti
errors.invalid_kind = Jan walt'ata kasta
errors.help_not_configured = Aka servidor layku yanapaña janiw wakichatakiti
errors.body_is_required = Apayañatakix mä kuns qillqt'aña
errors.title_is_required = Qillqatamaru mä sutiy uchaña
errors.no_fingerprint_returned = Khitiruxa janiw lukana sarnaqäwi kutiyirikiti
titles.intro = {name} uñt'ayaña
titles.question = {name} jiskt'awipa
errors.body_too_long = Arumaxa sinti jach'awa
errors.title_too_long = Sutimaxa sinti jach'awa
titles.someone = Khitisa
