[labels]
app.name = Yanapt'a
errors.invalid_kind = Jan walt'ata kasta
errors.help_not_configured = Aka servidortakix yanapa janiw wakichatäkiti
errors.body_is_required = Janïr apayasax juk'amp detallenak yapxatam
errors.title_is_required = Qillqatamar mä título uchaña
errors.no_fingerprint_returned = Destinox janiw fingerprint kutt'aykiti
titles.intro = {name} uñt'ayaña
errors.body_too_long = Mensajemax sinti jach'awa
errors.title_too_long = Títulomax sinti jach'awa
errors.unknown_document = Jan uñt'ata documento
errors.remote_failed = Jaya mayiwix pantjawayi
errors.service_unavailable = Apayañ servicio jichhax janiw utjkiti. Qhipat wasitat yant'am.
titles.someone = Khitisa

errors.invalid_id = ID jan walikiti
errors.invalid_project_id = Proyecto ID jan walikiti
errors.forum_not_found = Foro jan jikxatasiti
errors.forum_not_found_in_directory = Foro directorion jan jikxatasiti
errors.not_allowed_to_post = Qillqañax janiw iyawsatäkiti
errors.project_not_found = Proyecto jan jikxatasiti
errors.access_denied = Mantañ jark'ata
errors.unable_to_find_project_in_directory = Directorion proyecto janiw jikxatañjamäkiti
errors.remote = Jaya servidorax janiw mayiwi tukuyañ atkiti

errors.unable_to_connect_to_server = Servidorar janiw chikacht'asiñjamäkiti
errors.could_not_reach_project_owner = Proyecto dueñopar janiw puriñjamäkänti
errors.no_object_returned = Proyecton dueñopax janiw machaq item kutt'aykiti
errors.invalid_post_id = Qillqata ID jan walikiti
errors.invalid_title = Título jan walikiti
errors.invalid_body = Contenido jan walikiti
