[labels]
app.name = Kömək
errors.not_logged_in = Daxil olmamısınız
errors.invalid_kind = Yararsız növ
errors.help_not_configured = Bu server üçün kömək konfiqurasiya edilməyib
errors.body_is_required = Göndərmədən əvvəl lütfən nəsə yazın
errors.title_is_required = Lütfən paylaşımınıza başlıq verin
errors.no_fingerprint_returned = Təyinat barmaq izi qaytarmadı
titles.intro = {name} ilə tanış olun
errors.body_too_long = Mesajınız çox uzundur
errors.title_too_long = Başlığınız çox uzundur
errors.unknown_document = Naməlum sənəd
errors.remote_failed = Uzaq sorğu uğursuz oldu
errors.service_unavailable = Göndərmə xidməti müvəqqəti olaraq əlçatan deyil. Zəhmət olmasa, daha sonra yenidən cəhd edin.
titles.someone = Kimsə

errors.invalid_id = Etibarsız ID
errors.invalid_project_id = Etibarsız layihə ID
errors.forum_not_found = Forum tapılmadı
errors.forum_not_found_in_directory = Forum kataloqda tapılmadı
errors.not_allowed_to_post = Post yazmağa icazə verilmir
errors.project_not_found = Layihə tapılmadı
errors.access_denied = Giriş qadağandır
errors.you_own_this_project = Bu layihə sizindir
errors.unable_to_find_project_in_directory = Layihəni kataloqda tapmaq mümkün deyil
errors.remote = Uzaq server sorğunu tamamlaya bilmədi
