[labels]
app.name = Дапамога
errors.not_logged_in = Не выкананы ўваход
errors.invalid_kind = Несапраўдны тып
errors.help_not_configured = Даведка не настроена для гэтага сервера
errors.body_is_required = Увядзіце тэкст перад адпраўкай
errors.title_is_required = Дайце загаловак вашай публікацыі
errors.no_fingerprint_returned = Атрымальнік не вярнуў адбітак
titles.intro = Прадстаўляем {name}
errors.body_too_long = Ваша паведамленне занадта доўгае
errors.title_too_long = Ваш загаловак занадта доўгі
errors.unknown_document = Невядомы дакумент
errors.remote_failed = Аддалены запыт не выкананы
errors.service_unavailable = Сэрвіс адпраўкі часова недаступны. Калі ласка, паспрабуйце пазней.
titles.someone = Хтосьці

errors.invalid_id = Некарэктны ID
errors.invalid_project_id = Некарэктны ID праекта
errors.forum_not_found = Форум не знойдзены
errors.forum_not_found_in_directory = Форум не знойдзены ў каталогу
errors.not_allowed_to_post = Не дазволена публікаваць
errors.project_not_found = Праект не знойдзены
errors.access_denied = Доступ забаронены
errors.you_own_this_project = Вы валодаеце гэтым праектам
errors.unable_to_find_project_in_directory = Не ўдалося знайсці праект у каталогу
errors.remote = Аддалены сервер не змог выканаць запыт
