[labels]
app.name = Дапамога
errors.not_logged_in = Не выкананы ўваход
errors.invalid_kind = Несапраўдны тып
errors.help_not_configured = Даведка не настроена для гэтага сервера
errors.body_is_required = Увядзіце тэкст перад адпраўкай
errors.title_is_required = Дайце загаловак вашай публікацыі
errors.no_fingerprint_returned = Атрымальнік не вярнуў адбітак
titles.intro = Прадстаўляем {name}
errors.body_too_long = Ваша паведамленне занадта доўгае
errors.title_too_long = Ваш загаловак занадта доўгі
errors.unknown_document = Невядомы дакумент
errors.remote_failed = Аддалены запыт не выкананы
titles.someone = Хтосьці
