[labels]
app.name = Помощ
errors.not_logged_in = Не сте влезли
errors.invalid_kind = Невалиден вид
errors.help_not_configured = Помощта не е конфигурирана за този сървър
errors.body_is_required = Напишете нещо преди да изпратите
errors.title_is_required = Въведете заглавие на публикацията
errors.no_fingerprint_returned = Получателят не върна отпечатък
titles.intro = Представяме ви {name}
errors.body_too_long = Съобщението ви е твърде дълго
errors.title_too_long = Заглавието ви е твърде дълго
titles.someone = Някой
