[labels]
app.name = मदद
errors.not_logged_in = लॉग इन नइखीं
errors.invalid_kind = अमान्य प्रकार
errors.help_not_configured = ई सर्वर खातिर मदद कॉन्फ़िगर नइखे कइल
errors.body_is_required = कृपया सबमिट करे से पहिले कुछ लिखीं
errors.title_is_required = कृपया आपन पोस्ट के एगो शीर्षक दीं
errors.no_fingerprint_returned = गंतव्य फिंगरप्रिंट वापस ना भेजलस
titles.intro = प्रस्तुत बा {name}
titles.question = {name} के ओर से एगो सवाल
errors.body_too_long = रउआ के संदेश बहुत लंबा बा
errors.title_too_long = रउआ के शीर्षक बहुत लंबा बा
titles.someone = केहू
