[labels]
app.name = সাহায্য
errors.not_logged_in = লগ ইন করা নেই
errors.invalid_kind = অবৈধ প্রকার
errors.help_not_configured = এই সার্ভারের জন্য সাহায্য কনফিগার করা নেই
errors.body_is_required = অনুগ্রহ করে জমা দেওয়ার আগে কিছু লিখুন
errors.title_is_required = অনুগ্রহ করে আপনার পোস্টের একটি শিরোনাম দিন
errors.no_fingerprint_returned = গন্তব্য কোনো ফিঙ্গারপ্রিন্ট ফেরত দেয়নি
titles.intro = পরিচয় করিয়ে দিচ্ছি {name}
errors.body_too_long = আপনার বার্তাটি অনেক বড়
errors.title_too_long = আপনার শিরোনামটি অনেক বড়
errors.unknown_document = অজানা ডকুমেন্ট
errors.remote_failed = দূরবর্তী অনুরোধ ব্যর্থ হয়েছে
errors.service_unavailable = জমা দেওয়ার পরিষেবা সাময়িকভাবে অনুপলব্ধ। অনুগ্রহ করে পরে আবার চেষ্টা করুন।
titles.someone = কেউ একজন

errors.invalid_id = অবৈধ ID
errors.invalid_project_id = অবৈধ প্রজেক্ট ID
errors.forum_not_found = Forum পাওয়া যায়নি
errors.forum_not_found_in_directory = ডিরেক্টরিতে forum পাওয়া যায়নি
errors.not_allowed_to_post = পোস্ট করার অনুমতি নেই
errors.project_not_found = প্রজেক্ট পাওয়া যায়নি
errors.access_denied = অ্যাক্সেস অস্বীকৃত
errors.you_own_this_project = আপনি এই প্রজেক্টের মালিক
errors.unable_to_find_project_in_directory = ডিরেক্টরিতে প্রজেক্ট খুঁজে পেতে অক্ষম
errors.remote = দূরবর্তী সার্ভার অনুরোধটি সম্পন্ন করতে পারেনি
