[labels]
app.name = Pomoć
errors.not_logged_in = Niste prijavljeni
errors.invalid_kind = Nevažeća vrsta
errors.help_not_configured = Pomoć nije konfigurirana za ovaj server
errors.body_is_required = Napišite nešto prije slanja
errors.title_is_required = Unesite naslov objave
errors.no_fingerprint_returned = Odredište nije vratilo otisak
titles.intro = Predstavljamo {name}
errors.body_too_long = Vaša poruka je predugačka
errors.title_too_long = Vaš naslov je predugačak
errors.unknown_document = Nepoznat dokument
errors.remote_failed = Udaljeni zahtjev nije uspio
errors.service_unavailable = Usluga za slanje trenutno nije dostupna. Molimo pokušajte ponovo kasnije.
titles.someone = Neko

errors.invalid_id = Nevažeći ID
errors.invalid_project_id = Nevažeći ID projekta
errors.forum_not_found = Forum nije pronađen
errors.forum_not_found_in_directory = Forum nije pronađen u direktoriju
errors.not_allowed_to_post = Nije dozvoljeno objavljivanje
errors.project_not_found = Projekat nije pronađen
errors.access_denied = Pristup odbijen
errors.you_own_this_project = Vlasnik ste ovog projekta
errors.unable_to_find_project_in_directory = Nije moguće pronaći projekat u direktoriju
errors.remote = Udaljeni server nije mogao dovršiti zahtjev
