[labels]
app.name = Ajuda
errors.not_logged_in = Sessió no iniciada
errors.invalid_kind = Tipus no vàlid
errors.help_not_configured = L'ajuda no està configurada per a aquest servidor
errors.body_is_required = Escriu alguna cosa abans d'enviar
errors.title_is_required = Afegeix un títol a la teva publicació
errors.no_fingerprint_returned = La destinació no ha retornat cap empremta
titles.intro = Us presentem {name}
errors.body_too_long = El teu missatge és massa llarg
errors.title_too_long = El teu títol és massa llarg
errors.unknown_document = Document desconegut
errors.remote_failed = La sol·licitud remota ha fallat
titles.someone = Algú
