[labels]
app.name = Ajuda
errors.not_logged_in = Sessió no iniciada
errors.invalid_kind = Tipus no vàlid
errors.help_not_configured = L'ajuda no està configurada per a aquest servidor
errors.body_is_required = Escriu alguna cosa abans d'enviar
errors.title_is_required = Afegeix un títol a la teva publicació
errors.no_fingerprint_returned = La destinació no ha retornat cap empremta
titles.intro = Us presentem {name}
errors.body_too_long = El teu missatge és massa llarg
errors.title_too_long = El teu títol és massa llarg
errors.unknown_document = Document desconegut
errors.remote_failed = La sol·licitud remota ha fallat
errors.service_unavailable = El servei d'enviament no està disponible temporalment. Torneu-ho a provar més tard.
titles.someone = Algú

errors.invalid_id = Identificador no vàlid
errors.invalid_project_id = Identificador de projecte no vàlid
errors.forum_not_found = No s'ha trobat el fòrum
errors.forum_not_found_in_directory = No s'ha trobat el fòrum al directori
errors.not_allowed_to_post = No permès publicar
errors.project_not_found = No s'ha trobat el projecte
errors.access_denied = Accés denegat
errors.you_own_this_project = Aquest projecte és teu
errors.unable_to_find_project_in_directory = No s'ha pogut trobar el projecte al directori
errors.remote = El servidor remot no ha pogut completar la sol·licitud
