[labels]
app.name = یارمەتی
errors.not_logged_in = نەچوویتە ژوورەوە
errors.invalid_kind = جۆری نادروست
errors.help_not_configured = یارمەتی بۆ ئەم ڕاژەکارە ڕێکنەخراوە
errors.body_is_required = تکایە پێش ناردن شتێک بنووسە
errors.title_is_required = تکایە ناونیشانێک بدە بە بابەتەکەت
errors.no_fingerprint_returned = مەبەست هیچ پەنجەمۆرێکی نەگەڕاندەوە
titles.intro = ناساندنی {name}
errors.body_too_long = نامەکەت زۆر درێژە
errors.title_too_long = ناونیشانەکەت زۆر درێژە
errors.unknown_document = بەڵگەنامەی نەناسراو
errors.remote_failed = داواکاری دوور سەرکەوتوو نەبوو
errors.service_unavailable = خزمەتگوزاری ناردن بۆ ماوەیەکی کاتی بەردەست نییە. تکایە دواتر دووبارە هەوڵ بدەرەوە.
titles.someone = کەسێک

errors.invalid_id = ناسنامەی نادروست
errors.invalid_project_id = ناسنامەی پڕۆژەی نادروست
errors.forum_not_found = فۆڕەم نەدۆزرایەوە
errors.forum_not_found_in_directory = فۆڕەم لە ڕێنماییدا نەدۆزرایەوە
errors.not_allowed_to_post = ڕێگە نەدراوە بۆ پۆستکردن
errors.project_not_found = پڕۆژە نەدۆزرایەوە
errors.access_denied = ڕێگە نەدراوە
errors.you_own_this_project = تۆ خاوەنی ئەم پڕۆژەیەی
errors.unable_to_find_project_in_directory = ناتوانرێت پڕۆژە لە ڕێنماییدا بدۆزرێتەوە
errors.remote = ڕاژەکاری دوور نەیتوانی داواکارییەکە تەواو بکات
