[labels]
app.name = Cymorth
errors.not_logged_in = Heb fewngofnodi
errors.invalid_kind = Math annilys
errors.help_not_configured = Nid yw'r cymorth wedi'i ffurfweddu ar gyfer y gweinydd hwn
errors.body_is_required = Teipiwch rywbeth cyn cyflwyno
errors.title_is_required = Rhowch deitl i'ch post
errors.no_fingerprint_returned = Ni ddychwelodd y cyrchfan olion bysedd
titles.intro = Cyflwyno {name}
errors.body_too_long = Mae eich neges yn rhy hir
errors.title_too_long = Mae eich teitl yn rhy hir
errors.unknown_document = Dogfen anhysbys
errors.remote_failed = Methodd y cais o bell
errors.service_unavailable = Nid yw'r gwasanaeth cyflwyno ar gael dros dro. Rhowch gynnig arall arni yn nes ymlaen.
titles.someone = Rhywun

errors.invalid_id = ID annilys
errors.invalid_project_id = ID prosiect annilys
errors.forum_not_found = Fforwm heb ei ganfod
errors.forum_not_found_in_directory = Fforwm heb ei ganfod yn y cyfeiriadur
errors.not_allowed_to_post = Ni chaniateir postio
errors.project_not_found = Prosiect heb ei ganfod
errors.access_denied = Mynediad wedi'i wrthod
errors.you_own_this_project = Rydych yn berchen ar y prosiect hwn
errors.unable_to_find_project_in_directory = Methu canfod prosiect yn y cyfeiriadur
errors.remote = Ni allai'r gweinydd pell gwblhau'r cais
