[labels]
app.name = Cymorth
errors.not_logged_in = Heb fewngofnodi
errors.invalid_kind = Math annilys
errors.help_not_configured = Nid yw'r cymorth wedi'i ffurfweddu ar gyfer y gweinydd hwn
errors.body_is_required = Teipiwch rywbeth cyn cyflwyno
errors.title_is_required = Rhowch deitl i'ch post
errors.no_fingerprint_returned = Ni ddychwelodd y cyrchfan olion bysedd
titles.intro = Cyflwyno {name}
errors.body_too_long = Mae eich neges yn rhy hir
errors.title_too_long = Mae eich teitl yn rhy hir
errors.unknown_document = Dogfen anhysbys
errors.remote_failed = Methodd y cais o bell
titles.someone = Rhywun
