[labels]
app.name = Hjælp
errors.not_logged_in = Ikke logget ind
errors.invalid_kind = Ugyldig type
errors.help_not_configured = Hjælp er ikke konfigureret for denne server
errors.body_is_required = Skriv noget, før du sender
errors.title_is_required = Giv dit indlæg en titel
errors.no_fingerprint_returned = Destinationen returnerede ikke et fingeraftryk
titles.intro = Mød {name}
errors.body_too_long = Din besked er for lang
errors.title_too_long = Din titel er for lang
errors.unknown_document = Ukendt dokument
errors.remote_failed = Fjernanmodning mislykkedes
titles.someone = Nogen
