[labels]
app.name = Hilfe
errors.not_logged_in = Nicht angemeldet
errors.invalid_kind = Ungültiger Typ
errors.help_not_configured = Hilfe ist für diesen Server nicht konfiguriert
errors.body_is_required = Bitte gib etwas ein, bevor du absendest
errors.title_is_required = Bitte gib deinem Beitrag einen Titel
errors.no_fingerprint_returned = Das Ziel hat keinen Fingerabdruck zurückgegeben
titles.intro = Wir stellen vor: {name}
titles.question = Eine Frage von {name}
errors.body_too_long = Deine Nachricht ist zu lang
errors.title_too_long = Dein Titel ist zu lang
titles.someone = Jemand
