[labels]
app.name = Βοήθεια
errors.not_logged_in = Δεν έχετε συνδεθεί
errors.invalid_kind = Μη έγκυρος τύπος
errors.help_not_configured = Η βοήθεια δεν έχει ρυθμιστεί για αυτόν τον διακομιστή
errors.body_is_required = Πληκτρολογήστε κάτι πριν την υποβολή
errors.title_is_required = Δώστε έναν τίτλο στην ανάρτησή σας
errors.no_fingerprint_returned = Ο προορισμός δεν επέστρεψε αποτύπωμα
titles.intro = Σας παρουσιάζουμε το {name}
errors.body_too_long = Το μήνυμά σας είναι πολύ μεγάλο
errors.title_too_long = Ο τίτλος σας είναι πολύ μεγάλος
errors.unknown_document = Άγνωστο έγγραφο
errors.remote_failed = Το απομακρυσμένο αίτημα απέτυχε
errors.service_unavailable = Η υπηρεσία υποβολής δεν είναι προσωρινά διαθέσιμη. Δοκιμάστε ξανά αργότερα.
titles.someone = Κάποιος

errors.invalid_id = Μη έγκυρο ID
errors.invalid_project_id = Μη έγκυρο ID έργου
errors.forum_not_found = Δεν βρέθηκε το forum
errors.forum_not_found_in_directory = Δεν βρέθηκε το forum στον κατάλογο
errors.not_allowed_to_post = Δεν επιτρέπεται η ανάρτηση
errors.project_not_found = Δεν βρέθηκε το έργο
errors.access_denied = Άρνηση πρόσβασης
errors.you_own_this_project = Είστε ιδιοκτήτης αυτού του έργου
errors.unable_to_find_project_in_directory = Αδυναμία εύρεσης έργου στον κατάλογο
errors.remote = Ο απομακρυσμένος διακομιστής δεν μπόρεσε να ολοκληρώσει το αίτημα
