[labels]
app.name = Abi
errors.not_logged_in = Pole sisse logitud
errors.invalid_kind = Vigane tüüp
errors.help_not_configured = Abi pole selle serveri jaoks seadistatud
errors.body_is_required = Kirjuta midagi enne saatmist
errors.title_is_required = Anna oma postitusele pealkiri
errors.no_fingerprint_returned = Sihtkoht ei tagastanud sõrmejälge
titles.intro = Tutvustame: {name}
errors.body_too_long = Sinu sõnum on liiga pikk
errors.title_too_long = Sinu pealkiri on liiga pikk
titles.someone = Keegi
