[labels]
app.name = Abi
errors.not_logged_in = Pole sisse logitud
errors.invalid_kind = Vigane tüüp
errors.help_not_configured = Abi pole selle serveri jaoks seadistatud
errors.body_is_required = Kirjuta midagi enne saatmist
errors.title_is_required = Anna oma postitusele pealkiri
errors.no_fingerprint_returned = Sihtkoht ei tagastanud sõrmejälge
titles.intro = Tutvustame: {name}
errors.body_too_long = Sinu sõnum on liiga pikk
errors.title_too_long = Sinu pealkiri on liiga pikk
errors.unknown_document = Tundmatu dokument
errors.remote_failed = Kaugpäring ebaõnnestus
errors.service_unavailable = Esitamisteenus on ajutiselt kättesaamatu. Palun proovige hiljem uuesti.
titles.someone = Keegi

errors.invalid_id = Vigane ID
errors.invalid_project_id = Vigane projekti ID
errors.forum_not_found = Foorumit ei leitud
errors.forum_not_found_in_directory = Foorumit ei leitud kataloogist
errors.not_allowed_to_post = Postitamine pole lubatud
errors.project_not_found = Projekti ei leitud
errors.access_denied = Juurdepääs keelatud
errors.you_own_this_project = See projekt kuulub sulle
errors.unable_to_find_project_in_directory = Projekti ei leitud kataloogist
errors.remote = Kaugserver ei suutnud päringut lõpule viia
