[labels]
app.name = Laguntza
errors.not_logged_in = Saioa hasi gabe
errors.invalid_kind = Mota baliogabea
errors.help_not_configured = Laguntza ez dago zerbitzari honetarako konfiguratuta
errors.body_is_required = Idatzi zerbait bidali aurretik
errors.title_is_required = Eman izenburua zure argitalpenari
errors.no_fingerprint_returned = Helburuak ez du hatz-marka itzuli
titles.intro = {name} aurkezten dizugu
errors.body_too_long = Zure mezua luzeegia da
errors.title_too_long = Zure izenburua luzeegia da
titles.someone = Norbait
