[labels]
app.name = Ohje
errors.invalid_kind = Virheellinen tyyppi
errors.help_not_configured = Ohjetta ei ole määritetty tälle palvelimelle
errors.body_is_required = Kirjoita jotakin ennen lähettämistä
errors.title_is_required = Anna julkaisullesi otsikko
errors.no_fingerprint_returned = Kohde ei palauttanut sormenjälkeä
titles.intro = Esittelyssä {name}
errors.body_too_long = Viestisi on liian pitkä
errors.title_too_long = Otsikkosi on liian pitkä
errors.unknown_document = Tuntematon dokumentti
errors.remote_failed = Etäpyyntö epäonnistui
errors.service_unavailable = Lähetyspalvelu ei ole tilapäisesti käytettävissä. Yritä myöhemmin uudelleen.
titles.someone = Joku

errors.invalid_id = Virheellinen tunnus
errors.invalid_project_id = Virheellinen projektin tunnus
errors.forum_not_found = Foorumia ei löytynyt
errors.forum_not_found_in_directory = Foorumia ei löytynyt hakemistosta
errors.not_allowed_to_post = Julkaiseminen ei ole sallittu
errors.project_not_found = Projektia ei löytynyt
errors.access_denied = Pääsy evätty
errors.you_own_this_project = Omistat tämän projektin
errors.unable_to_find_project_in_directory = Projektia ei löytynyt hakemistosta
errors.remote = Etäpalvelin ei voinut suorittaa pyyntöä loppuun

errors.unable_to_connect_to_server = Palvelimeen ei voitu yhdistää
errors.could_not_reach_project_owner = Projektin omistajaa ei tavoitettu
errors.no_object_returned = Projektin omistaja ei palauttanut uutta kohdetta
errors.invalid_post_id = Virheellinen julkaisun tunnus
errors.invalid_title = Virheellinen otsikko
errors.invalid_body = Virheellinen sisältö
