[labels]
app.name = Aide
errors.not_logged_in = Non connecté
errors.invalid_kind = Type invalide
errors.help_not_configured = L'aide n'est pas configurée pour ce serveur
errors.body_is_required = Veuillez saisir un texte avant d'envoyer
errors.title_is_required = Veuillez donner un titre à votre publication
errors.no_fingerprint_returned = La destination n'a pas renvoyé d'empreinte
titles.intro = Présentation de {name}
titles.question = Une question de {name}
errors.body_too_long = Votre message est trop long
errors.title_too_long = Votre titre est trop long
titles.someone = Quelqu'un
