[labels]
app.name = Cabhair
errors.not_logged_in = Níl tú logáilte isteach
errors.invalid_kind = Cineál neamhbhailí
errors.help_not_configured = Níl an chabhair cumraithe don fhreastalaí seo
errors.body_is_required = Clóscríobh rud éigin sula seolfaidh tú
errors.title_is_required = Tabhair teideal don phostáil
errors.no_fingerprint_returned = Níor sheol an ceann scríbe méarlorg ar ais
titles.intro = Cuirimid {name} i láthair
errors.body_too_long = Tá do theachtaireacht ró-fhada
errors.title_too_long = Tá do theideal ró-fhada
errors.unknown_document = Doiciméad anaithnid
errors.remote_failed = Theip ar iarratas cianda
errors.service_unavailable = Tá an tseirbhís aighneachta ar fáil go sealadach. Bain triail eile as ar ball.
titles.someone = Duine éigin

errors.invalid_id = ID neamhbhailí
errors.invalid_project_id = ID tionscadail neamhbhailí
errors.forum_not_found = Fóram gan aimsiú
errors.forum_not_found_in_directory = Fóram gan aimsiú san eolaire
errors.not_allowed_to_post = Gan cead postáil
errors.project_not_found = Tionscadal gan aimsiú
errors.access_denied = Rochtain diúltaithe
errors.you_own_this_project = Is leatsa an tionscadal seo
errors.unable_to_find_project_in_directory = Ní féidir tionscadal a aimsiú san eolaire
errors.remote = Níorbh fhéidir leis an bhfreastalaí cianda an t-iarratas a chur i gcrích
