[labels]
app.name = Cobhair
errors.not_logged_in = Chan eil thu air clàradh a-steach
errors.invalid_kind = Seòrsa mì-dhligheach
errors.help_not_configured = Chan eil a' chobhair air a rèiteachadh airson an fhrithealaiche seo
errors.body_is_required = Sgrìobh rudeigin mus cuir thu a-steach e
errors.title_is_required = Thoir tiotal don phostadh agad
errors.no_fingerprint_returned = Cha do thill an ceann-uidhe meur-lorg
titles.intro = A' toirt a-steach {name}
titles.question = Ceist bho {name}
errors.body_too_long = Tha an teachdaireachd agad ro fhada
errors.title_too_long = Tha an tiotal agad ro fhada
titles.someone = Cuideigin
