[labels]
app.name = Cobhair
errors.not_logged_in = Chan eil thu air clàradh a-steach
errors.invalid_kind = Seòrsa mì-dhligheach
errors.help_not_configured = Chan eil a' chobhair air a rèiteachadh airson an fhrithealaiche seo
errors.body_is_required = Sgrìobh rudeigin mus cuir thu a-steach e
errors.title_is_required = Thoir tiotal don phostadh agad
errors.no_fingerprint_returned = Cha do thill an ceann-uidhe meur-lorg
titles.intro = A' toirt a-steach {name}
errors.body_too_long = Tha an teachdaireachd agad ro fhada
errors.title_too_long = Tha an tiotal agad ro fhada
errors.unknown_document = Sgrìobhainn neo-aithnichte
errors.remote_failed = Dh'fhàillig an t-iarrtas iomallach
errors.service_unavailable = Chan eil an t-seirbheis tagraidh ri fhaighinn rè ùine. Feuch ris a-rithist an ceann tamaill.
titles.someone = Cuideigin

errors.invalid_id = ID mì-dhligheach
errors.invalid_project_id = ID pròiseict mì-dhligheach
errors.forum_not_found = Cha deach am fòraman a lorg
errors.forum_not_found_in_directory = Cha deach am fòraman a lorg san eòlaire
errors.not_allowed_to_post = Chan eil cead postachadh
errors.project_not_found = Cha deach am pròiseact a lorg
errors.access_denied = Inntrigeadh air a dhiùltadh
errors.you_own_this_project = Is leatsa am pròiseact seo
errors.unable_to_find_project_in_directory = Cha b' urrainnear pròiseact a lorg san eòlaire
errors.remote = Cha b' urrainn dhan fhrithealaiche chèin an t-iarrtas a choileanadh
