[labels]
app.name = Axuda
errors.not_logged_in = Sesión non iniciada
errors.invalid_kind = Tipo non válido
errors.help_not_configured = A axuda non está configurada para este servidor
errors.body_is_required = Escribe algo antes de enviar
errors.title_is_required = Engade un título á túa publicación
errors.no_fingerprint_returned = O destino non devolveu unha pegada
titles.intro = Presentámosche {name}
errors.body_too_long = A túa mensaxe é demasiado longa
errors.title_too_long = O teu título é demasiado longo
titles.someone = Alguén
