[labels]
app.name = Pytyvõ
errors.not_logged_in = Nereikéi
errors.invalid_kind = Mba'eichagua hekopegua'ỹva
errors.help_not_configured = Ko servidor-pe ndaiporiri pytyvõ ñembosako'ipy
errors.body_is_required = Embohasa mboyve ehai mba'e
errors.title_is_required = Eme'ẽ peteĩ tera ne mbohasa rehegua
errors.no_fingerprint_returned = Pe ohohápe nombojevýiri kuãhũ
titles.intro = Roikuaauka ndéve {name}
errors.body_too_long = Nde marandu ipukueterei
errors.title_too_long = Nde téra ipukueterei
errors.unknown_document = Documento ojekuaa'ỹva
errors.remote_failed = Mombyry jerure ndoikói
errors.service_unavailable = Pe ñemondo mba'apoha ndaipóri sapy'aitérã. Eha'ã jey ag̃amieve.
titles.someone = Avave

errors.invalid_id = ID ndovaléi
errors.invalid_project_id = ID proyecto ndovaléi
errors.forum_not_found = Ndojejuhúi forum
errors.forum_not_found_in_directory = Ndojejuhúi forum directorio-pe
errors.not_allowed_to_post = Ndoheja'i oposta
errors.project_not_found = Ndojejuhúi proyecto
errors.access_denied = Ndojeheja jeike
errors.you_own_this_project = Nde ja'a ko proyecto
errors.unable_to_find_project_in_directory = Ndaikatúi ojejuhu proyecto directorio-pe
errors.remote = Pe servidor mombyry ndaikatúi omoĩmba pe jerure
