[labels]
app.name = Pytyvõ
errors.invalid_kind = Mba'eichagua hekopegua'ỹva
errors.help_not_configured = Ko mohendahápe pytyvõ noñembosako'íri
errors.body_is_required = Embojoapy michĩmi mba'e ñemombe'u embohasa mboyve
errors.title_is_required = Eme'ẽ peteĩ teratee ne marandúpe
errors.no_fingerprint_returned = Destino nombojevýi fingerprint
titles.intro = Roikuaauka ndéve {name}
errors.body_too_long = Ne ñe'ẽmondo ipuku eterei
errors.title_too_long = Ne teratee ipuku eterei
errors.unknown_document = Documento ojekuaa'ỹva
errors.remote_failed = Mombyry jerure ndoikói
errors.service_unavailable = Ñemondo servicio ndaipóri sapy'ami. Eha'ã jey ag̃amieve.
titles.someone = Peteĩ tapicha

errors.invalid_id = ID ndovaléi
errors.invalid_project_id = ID proyecto ndovaléi
errors.forum_not_found = Ndojejuhúi foro
errors.forum_not_found_in_directory = Ndojejuhúi foro directorio-pe
errors.not_allowed_to_post = Ndoheja'i omoherakuã
errors.project_not_found = Ndojejuhúi proyecto
errors.access_denied = Jeike noñemoneĩri
errors.unable_to_find_project_in_directory = Ndaikatúi ojejuhu proyecto directorio-pe
errors.remote = Mohendaha mombyrygua ndaikatúi omohu'ã jerure

errors.unable_to_connect_to_server = Ndaikatúi oñembojoaju mohendahápe
errors.could_not_reach_project_owner = Ndaikatúi oñeñemboja proyecto járare
errors.no_object_returned = Proyecto jára ndoguerúi pe mba'e pyahu
errors.invalid_post_id = ID marandu ndovaléi
errors.invalid_title = Teratee ndovaléi
errors.invalid_body = Jehaipyre ndovaléi
