[labels]
app.name = Pytyvõ
errors.not_logged_in = Nereikéi
errors.invalid_kind = Mba'eichagua hekopegua'ỹva
errors.help_not_configured = Ko servidor-pe ndaiporiri pytyvõ ñembosako'ipy
errors.body_is_required = Embohasa mboyve ehai mba'e
errors.title_is_required = Eme'ẽ peteĩ tera ne mbohasa rehegua
errors.no_fingerprint_returned = Pe ohohápe nombojevýiri kuãhũ
titles.intro = Roikuaauka ndéve {name}
titles.question = Porandu {name} mba'éva
errors.body_too_long = Nde marandu ipukueterei
errors.title_too_long = Nde téra ipukueterei
titles.someone = Avave
