[labels]
app.name = મદદ
errors.not_logged_in = લૉગ ઇન નથી
errors.invalid_kind = અમાન્ય પ્રકાર
errors.help_not_configured = આ સર્વર માટે મદદ રૂપરેખાંકિત નથી
errors.body_is_required = કૃપા કરીને સબમિટ કરતા પહેલા કંઈક લખો
errors.title_is_required = કૃપા કરીને તમારી પોસ્ટને શીર્ષક આપો
errors.no_fingerprint_returned = ગંતવ્યે ફિંગરપ્રિન્ટ પરત કરી નથી
titles.intro = પ્રસ્તુત છે {name}
errors.body_too_long = તમારો સંદેશ ખૂબ લાંબો છે
errors.title_too_long = તમારું શીર્ષક ખૂબ લાંબું છે
errors.unknown_document = અજાણ્યો દસ્તાવેજ
errors.remote_failed = દૂરસ્થ વિનંતી નિષ્ફળ થઈ
errors.service_unavailable = સબમિશન સેવા હાલમાં અસ્થાયી રૂપે અનુપલબ્ધ છે. કૃપા કરીને થોડી વાર પછી ફરી પ્રયાસ કરો.
titles.someone = કોઈ

errors.invalid_id = અમાન્ય ID
errors.invalid_project_id = અમાન્ય પ્રોજેક્ટ ID
errors.forum_not_found = ફોરમ મળ્યું નથી
errors.forum_not_found_in_directory = ડિરેક્ટરીમાં ફોરમ મળ્યું નથી
errors.not_allowed_to_post = પોસ્ટ કરવાની મંજૂરી નથી
errors.project_not_found = પ્રોજેક્ટ મળ્યો નથી
errors.access_denied = એક્સેસ નકારાયો
errors.you_own_this_project = તમે આ પ્રોજેક્ટના માલિક છો
errors.unable_to_find_project_in_directory = ડિરેક્ટરીમાં પ્રોજેક્ટ શોધવામાં અસમર્થ
errors.remote = દૂરસ્થ સર્વર વિનંતી પૂર્ણ કરી શક્યું નથી
