[labels]
app.name = Taimako
errors.not_logged_in = Ba a shiga ba
errors.invalid_kind = Nau'i mara inganci
errors.help_not_configured = Ba a saita Taimako ba don wannan uwar garken
errors.body_is_required = Don Allah a buga wani abu kafin a aika
errors.title_is_required = Don Allah a ba da taken sakon ku
errors.no_fingerprint_returned = Wurin da aka aika bai dawo da yatsa ba
titles.intro = An gabatar da {name}
errors.body_too_long = Saƙonka ya yi tsawo sosai
errors.title_too_long = Taken naka ya yi tsawo sosai
errors.unknown_document = Takarda da ba a sani ba
errors.remote_failed = Bukatar nesa ta gaza
errors.service_unavailable = Sabis ɗin ƙaddamarwa ba ya samuwa na ɗan lokaci. Da fatan za a sake gwadawa daga baya.
titles.someone = Wani

errors.invalid_id = ID bai inganta ba
errors.invalid_project_id = ID na project bai inganta ba
errors.forum_not_found = Ba a sami forum ba
errors.forum_not_found_in_directory = Ba a sami forum a directory ba
errors.not_allowed_to_post = Ba a yarda da post ba
errors.project_not_found = Ba a sami project ba
errors.access_denied = An hana shiga
errors.you_own_this_project = Kana mallakar wannan project
errors.unable_to_find_project_in_directory = Ba a iya samun project a directory ba
errors.remote = Sabar mai nisa ba ta iya kammala buƙatar ba
