[labels]
app.name = सहायता
errors.not_logged_in = लॉग इन नहीं हैं
errors.invalid_kind = अमान्य प्रकार
errors.help_not_configured = इस सर्वर के लिए सहायता कॉन्फ़िगर नहीं की गई है
errors.body_is_required = कृपया सबमिट करने से पहले कुछ लिखें
errors.title_is_required = कृपया अपनी पोस्ट को एक शीर्षक दें
errors.no_fingerprint_returned = गंतव्य ने फ़िंगरप्रिंट नहीं लौटाया
titles.intro = प्रस्तुत है {name}
titles.question = {name} का एक प्रश्न
errors.body_too_long = आपका संदेश बहुत लंबा है
errors.title_too_long = आपका शीर्षक बहुत लंबा है
titles.someone = कोई
