[labels]
app.name = Pomoć
errors.not_logged_in = Niste prijavljeni
errors.invalid_kind = Nevažeća vrsta
errors.help_not_configured = Pomoć nije postavljena za ovaj poslužitelj
errors.body_is_required = Prije slanja nešto napišite
errors.title_is_required = Unesite naslov objave
errors.no_fingerprint_returned = Odredište nije vratilo otisak
titles.intro = Predstavljamo {name}
titles.question = Pitanje od {name}
errors.body_too_long = Vaša poruka je predugačka
errors.title_too_long = Vaš naslov je predugačak
titles.someone = Netko
