[labels]
app.name = Súgó
errors.not_logged_in = Nincs bejelentkezve
errors.invalid_kind = Érvénytelen típus
errors.help_not_configured = A súgó nincs beállítva ehhez a kiszolgálóhoz
errors.body_is_required = Írjon valamit a beküldés előtt
errors.title_is_required = Adjon címet a bejegyzésnek
errors.no_fingerprint_returned = A célpont nem adott vissza ujjlenyomatot
titles.intro = Bemutatjuk: {name}
errors.body_too_long = Az üzeneted túl hosszú
errors.title_too_long = A címed túl hosszú
errors.unknown_document = Ismeretlen dokumentum
errors.remote_failed = A távoli kérés sikertelen
errors.service_unavailable = A beküldési szolgáltatás átmenetileg nem érhető el. Kérjük, próbálja meg később.
titles.someone = Valaki

errors.invalid_id = Érvénytelen azonosító
errors.invalid_project_id = Érvénytelen projekt azonosító
errors.forum_not_found = Fórum nem található
errors.forum_not_found_in_directory = Fórum nem található a címtárban
errors.not_allowed_to_post = Bejegyzés közzététele nem engedélyezett
errors.project_not_found = Projekt nem található
errors.access_denied = Hozzáférés megtagadva
errors.you_own_this_project = Ön a projekt tulajdonosa
errors.unable_to_find_project_in_directory = A projekt nem található a címtárban
errors.remote = A távoli kiszolgáló nem tudta teljesíteni a kérést
