[labels]
app.name = Súgó
errors.not_logged_in = Nincs bejelentkezve
errors.invalid_kind = Érvénytelen típus
errors.help_not_configured = A súgó nincs beállítva ehhez a kiszolgálóhoz
errors.body_is_required = Írjon valamit a beküldés előtt
errors.title_is_required = Adjon címet a bejegyzésnek
errors.no_fingerprint_returned = A célpont nem adott vissza ujjlenyomatot
titles.intro = Bemutatjuk: {name}
errors.body_too_long = Az üzeneted túl hosszú
errors.title_too_long = A címed túl hosszú
titles.someone = Valaki
