[labels]
app.name = Օգնություն
errors.not_logged_in = Մուտք գործած չեք
errors.invalid_kind = Անվավեր տեսակ
errors.help_not_configured = Այս սերվերի համար օգնությունը կարգավորված չէ
errors.body_is_required = Խնդրում ենք գրել ինչ-որ բան՝ նախքան ուղարկելը
errors.title_is_required = Խնդրում ենք ձեր գրառմանը վերնագիր տալ
errors.no_fingerprint_returned = Նպատակակետը մատնահետք չվերադարձրեց
titles.intro = Ներկայացնում ենք {name}-ին
errors.body_too_long = Ձեր հաղորդագրությունը չափազանց երկար է
errors.title_too_long = Ձեր վերնագիրը չափազանց երկար է
errors.unknown_document = Անհայտ փաստաթուղթ
errors.remote_failed = Հեռակա հարցումը ձախողվեց
errors.service_unavailable = Ներկայացման ծառայությունը ժամանակավորապես անհասանելի է: Խնդրում ենք փորձել կրկին ավելի ուշ:
titles.someone = Ինչ-որ մեկը

errors.invalid_id = Անվավեր ID
errors.invalid_project_id = Անվավեր նախագծի ID
errors.forum_not_found = Ֆորումը չի գտնվել
errors.forum_not_found_in_directory = Ֆորումը չի գտնվել ցուցակում
errors.not_allowed_to_post = Չի թույլատրվում գրառել
errors.project_not_found = Նախագիծը չի գտնվել
errors.access_denied = Մուտքն արգելված է
errors.you_own_this_project = Այս նախագծի սեփականատերը դուք եք
errors.unable_to_find_project_in_directory = Չհաջողվեց գտնել նախագիծը ցուցակում
errors.remote = Հեռավոր սերվերը չկարողացավ ավարտել հարցումը
