[labels]
app.name = Aiuto
errors.not_logged_in = Non hai effettuato l'accesso
errors.invalid_kind = Tipo non valido
errors.help_not_configured = L'aiuto non è configurato per questo server
errors.body_is_required = Scrivi qualcosa prima di inviare
errors.title_is_required = Aggiungi un titolo al tuo post
errors.no_fingerprint_returned = La destinazione non ha restituito un'impronta
titles.intro = Ti presentiamo {name}
errors.body_too_long = Il tuo messaggio è troppo lungo
errors.title_too_long = Il tuo titolo è troppo lungo
titles.someone = Qualcuno
