[labels]
app.name = ヘルプ
errors.not_logged_in = ログインしていません
errors.invalid_kind = 無効な種類
errors.help_not_configured = このサーバーにはヘルプが設定されていません
errors.body_is_required = 送信する前に何か入力してください
errors.title_is_required = 投稿にタイトルを付けてください
errors.no_fingerprint_returned = 宛先からフィンガープリントが返されませんでした
titles.intro = {name} のご紹介
errors.body_too_long = メッセージが長すぎます
errors.title_too_long = タイトルが長すぎます
errors.unknown_document = 不明なドキュメントです
errors.remote_failed = リモート要求に失敗しました
titles.someone = 誰か
