[labels]
app.name = დახმარება
errors.not_logged_in = შესული არ ხართ
errors.invalid_kind = არასწორი ტიპი
errors.help_not_configured = ამ სერვერისთვის დახმარება არ არის კონფიგურირებული
errors.body_is_required = გთხოვთ, გაგზავნამდე რაიმე აკრიფოთ
errors.title_is_required = გთხოვთ, თქვენს პოსტს სათაური დაარქვათ
errors.no_fingerprint_returned = დანიშნულების ადგილმა თითის ანაბეჭდი არ დააბრუნა
titles.intro = გაგაცნობთ {name}-ს
errors.body_too_long = თქვენი შეტყობინება ძალიან გრძელია
errors.title_too_long = თქვენი სათაური ძალიან გრძელია
errors.unknown_document = უცნობი დოკუმენტი
errors.remote_failed = დისტანციური მოთხოვნა ვერ შესრულდა
errors.service_unavailable = გაგზავნის სერვისი დროებით მიუწვდომელია. გთხოვთ, სცადოთ მოგვიანებით.
titles.someone = ვინმე

errors.invalid_id = არასწორი ID
errors.invalid_project_id = არასწორი პროექტის ID
errors.forum_not_found = ფორუმი ვერ მოიძებნა
errors.forum_not_found_in_directory = ფორუმი დირექტორიაში ვერ მოიძებნა
errors.not_allowed_to_post = პოსტირება არ არის დაშვებული
errors.project_not_found = პროექტი ვერ მოიძებნა
errors.access_denied = წვდომა აკრძალულია
errors.you_own_this_project = თქვენ ფლობთ ამ პროექტს
errors.unable_to_find_project_in_directory = პროექტის დირექტორიაში მოძებნა შეუძლებელია
errors.remote = დაშორებულმა სერვერმა ვერ შეასრულა მოთხოვნა
