[labels]
app.name = Анықтама
errors.not_logged_in = Жүйеге кірмегенсіз
errors.invalid_kind = Жарамсыз түр
errors.help_not_configured = Бұл сервер үшін көмек теңшелмеген
errors.body_is_required = Жіберер алдында бірдеңе теріңіз
errors.title_is_required = Жазбаңызға тақырып беріңіз
errors.no_fingerprint_returned = Тағайындау орны саусақ ізін қайтармады
titles.intro = {name} танысыңыз
errors.body_too_long = Хабарыңыз тым ұзын
errors.title_too_long = Тақырыбыңыз тым ұзын
titles.someone = Біреу
