[labels]
app.name = Анықтама
errors.not_logged_in = Жүйеге кірмегенсіз
errors.invalid_kind = Жарамсыз түр
errors.help_not_configured = Бұл сервер үшін көмек теңшелмеген
errors.body_is_required = Жіберер алдында бірдеңе теріңіз
errors.title_is_required = Жазбаңызға тақырып беріңіз
errors.no_fingerprint_returned = Тағайындау орны саусақ ізін қайтармады
titles.intro = {name} танысыңыз
errors.body_too_long = Хабарыңыз тым ұзын
errors.title_too_long = Тақырыбыңыз тым ұзын
errors.unknown_document = Белгісіз құжат
errors.remote_failed = Қашықтан сұрау орындалмады
errors.service_unavailable = Жіберу қызметі уақытша қолжетімсіз. Кейінірек қайталап көріңіз.
titles.someone = Біреу

errors.invalid_id = Жарамсыз ID
errors.invalid_project_id = Жарамсыз жоба ID
errors.forum_not_found = Форум табылмады
errors.forum_not_found_in_directory = Форум каталогта табылмады
errors.not_allowed_to_post = Жазба қалдыруға рұқсат жоқ
errors.project_not_found = Жоба табылмады
errors.access_denied = Қол жеткізуге тыйым салынды
errors.you_own_this_project = Сіз бұл жоба иесісіз
errors.unable_to_find_project_in_directory = Жобаны каталогта табу мүмкін емес
errors.remote = Қашықтағы сервер сұрауды аяқтай алмады
