[labels]
app.name = ಸಹಾಯ
errors.not_logged_in = ಲಾಗಿನ್ ಆಗಿಲ್ಲ
errors.invalid_kind = ಅಮಾನ್ಯ ಪ್ರಕಾರ
errors.help_not_configured = ಈ ಸರ್ವರ್‌ಗೆ ಸಹಾಯವನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಲಾಗಿಲ್ಲ
errors.body_is_required = ದಯವಿಟ್ಟು ಸಲ್ಲಿಸುವ ಮೊದಲು ಏನಾದರೂ ಟೈಪ್ ಮಾಡಿ
errors.title_is_required = ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪೋಸ್ಟ್‌ಗೆ ಶೀರ್ಷಿಕೆ ನೀಡಿ
errors.no_fingerprint_returned = ಗಮ್ಯಸ್ಥಾನವು ಫಿಂಗರ್‌ಪ್ರಿಂಟ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಲಿಲ್ಲ
titles.intro = ಪರಿಚಯಿಸಲಾಗುತ್ತಿದೆ {name}
titles.question = {name} ಅವರಿಂದ ಒಂದು ಪ್ರಶ್ನೆ
errors.body_too_long = ನಿಮ್ಮ ಸಂದೇಶವು ತುಂಬಾ ಉದ್ದವಾಗಿದೆ
errors.title_too_long = ನಿಮ್ಮ ಶೀರ್ಷಿಕೆ ತುಂಬಾ ಉದ್ದವಾಗಿದೆ
titles.someone = ಯಾರೋ
