[labels]
app.name = ಸಹಾಯ
errors.not_logged_in = ಲಾಗಿನ್ ಆಗಿಲ್ಲ
errors.invalid_kind = ಅಮಾನ್ಯ ಪ್ರಕಾರ
errors.help_not_configured = ಈ ಸರ್ವರ್‌ಗೆ ಸಹಾಯವನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಲಾಗಿಲ್ಲ
errors.body_is_required = ದಯವಿಟ್ಟು ಸಲ್ಲಿಸುವ ಮೊದಲು ಏನಾದರೂ ಟೈಪ್ ಮಾಡಿ
errors.title_is_required = ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪೋಸ್ಟ್‌ಗೆ ಶೀರ್ಷಿಕೆ ನೀಡಿ
errors.no_fingerprint_returned = ಗಮ್ಯಸ್ಥಾನವು ಫಿಂಗರ್‌ಪ್ರಿಂಟ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಲಿಲ್ಲ
titles.intro = ಪರಿಚಯಿಸಲಾಗುತ್ತಿದೆ {name}
errors.body_too_long = ನಿಮ್ಮ ಸಂದೇಶವು ತುಂಬಾ ಉದ್ದವಾಗಿದೆ
errors.title_too_long = ನಿಮ್ಮ ಶೀರ್ಷಿಕೆ ತುಂಬಾ ಉದ್ದವಾಗಿದೆ
errors.unknown_document = ಅಜ್ಞಾತ ಡಾಕ್ಯುಮೆಂಟ್
errors.remote_failed = ರಿಮೋಟ್ ವಿನಂತಿ ವಿಫಲವಾಗಿದೆ
errors.service_unavailable = ಸಲ್ಲಿಕೆ ಸೇವೆ ತಾತ್ಕಾಲಿಕವಾಗಿ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.
titles.someone = ಯಾರೋ

errors.invalid_id = ಅಮಾನ್ಯ ID
errors.invalid_project_id = ಅಮಾನ್ಯ ಪ್ರಾಜೆಕ್ಟ್ ID
errors.forum_not_found = ಫೋರಂ ಸಿಗಲಿಲ್ಲ
errors.forum_not_found_in_directory = ಡೈರೆಕ್ಟರಿಯಲ್ಲಿ ಫೋರಂ ಸಿಗಲಿಲ್ಲ
errors.not_allowed_to_post = ಪೋಸ್ಟ್ ಮಾಡಲು ಅನುಮತಿ ಇಲ್ಲ
errors.project_not_found = ಪ್ರಾಜೆಕ್ಟ್ ಸಿಗಲಿಲ್ಲ
errors.access_denied = ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ
errors.you_own_this_project = ನೀವು ಈ ಪ್ರಾಜೆಕ್ಟ್ ಅನ್ನು ಹೊಂದಿದ್ದೀರಿ
errors.unable_to_find_project_in_directory = ಡೈರೆಕ್ಟರಿಯಲ್ಲಿ ಪ್ರಾಜೆಕ್ಟ್ ಅನ್ನು ಹುಡುಕಲಾಗಲಿಲ್ಲ
errors.remote = ದೂರದ ಸರ್ವರ್ ವಿನಂತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ
