[labels]
app.name = Alîkarî
errors.not_logged_in = Têketin nehatiye kirin
errors.invalid_kind = Cureyê nederbasdar
errors.help_not_configured = Alîkarî ji bo vê serverê nehatiye veavakirin
errors.body_is_required = Berî şandinê tiştekî binivîse
errors.title_is_required = Ji kerema xwe sernavekê bide nivîsa xwe
errors.no_fingerprint_returned = Cihê armanc tu şopa tiliyê venegerand
titles.intro = Em {name} pêşkêş dikin
errors.body_too_long = Peyama te pir dirêj e
errors.title_too_long = Sernavê te pir dirêj e
titles.someone = Kesek
