[labels]
app.name = Жардам
errors.not_logged_in = Кирген жоксуз
errors.invalid_kind = Жараксыз түр
errors.help_not_configured = Бул сервер үчүн жардам конфигурацияланган эмес
errors.body_is_required = Жөнөтүүдөн мурун бир нерсе жазыңыз
errors.title_is_required = Постуңузга аталыш бериңиз
errors.no_fingerprint_returned = Дайындалуу орду манжа изин кайтарган жок
titles.intro = {name} менен таанышыңыз
titles.question = {name} жөнөткөн суроо
errors.body_too_long = Билдирүүңүз өтө узун
errors.title_too_long = Аталышыңыз өтө узун
titles.someone = Бирөө
