[labels]
app.name = Pagalba
errors.not_logged_in = Neprisijungęs
errors.invalid_kind = Netinkamas tipas
errors.help_not_configured = Pagalba nesukonfigūruota šiam serveriui
errors.body_is_required = Prieš siųsdami ką nors įrašykite
errors.title_is_required = Įveskite įrašo pavadinimą
errors.no_fingerprint_returned = Paskirties vieta negrąžino atspaudo
titles.intro = Pristatome {name}
errors.body_too_long = Jūsų žinutė per ilga
errors.title_too_long = Jūsų pavadinimas per ilgas
errors.unknown_document = Nežinomas dokumentas
errors.remote_failed = Nuotolinė užklausa nepavyko
errors.service_unavailable = Pateikimo paslauga laikinai nepasiekiama. Bandykite dar kartą vėliau.
titles.someone = Kažkas

errors.invalid_id = Netinkamas ID
errors.invalid_project_id = Netinkamas projekto ID
errors.forum_not_found = Forumas nerastas
errors.forum_not_found_in_directory = Forumas kataloge nerastas
errors.not_allowed_to_post = Neleidžiama skelbti
errors.project_not_found = Projektas nerastas
errors.access_denied = Prieiga atmesta
errors.you_own_this_project = Jūs valdote šį projektą
errors.unable_to_find_project_in_directory = Nepavyko rasti projekto kataloge
errors.remote = Nuotolinis serveris negalėjo įvykdyti užklausos
