[labels]
app.name = Pagalba
errors.not_logged_in = Neprisijungęs
errors.invalid_kind = Netinkamas tipas
errors.help_not_configured = Pagalba nesukonfigūruota šiam serveriui
errors.body_is_required = Prieš siųsdami ką nors įrašykite
errors.title_is_required = Įveskite įrašo pavadinimą
errors.no_fingerprint_returned = Paskirties vieta negrąžino atspaudo
titles.intro = Pristatome {name}
titles.question = Klausimas nuo {name}
errors.body_too_long = Jūsų žinutė per ilga
errors.title_too_long = Jūsų pavadinimas per ilgas
titles.someone = Kažkas
