[labels]
app.name = Palīdzība
errors.not_logged_in = Nav pieteicies
errors.invalid_kind = Nederīgs veids
errors.help_not_configured = Palīdzība šim serverim nav konfigurēta
errors.body_is_required = Lūdzu, ieraksti kaut ko pirms nosūtīšanas
errors.title_is_required = Lūdzu, piešķir savai ziņai virsrakstu
errors.no_fingerprint_returned = Galamērķis neatgrieza pirkstu nospiedumu
titles.intro = Iepazīstinām: {name}
errors.body_too_long = Jūsu ziņa ir pārāk gara
errors.title_too_long = Jūsu virsraksts ir pārāk garš
titles.someone = Kāds
