[labels]
app.name = Помош
errors.not_logged_in = Не сте најавени
errors.invalid_kind = Неважечки вид
errors.help_not_configured = Помошта не е конфигурирана за овој сервер
errors.body_is_required = Напишете нешто пред да испратите
errors.title_is_required = Внесете наслов на објавата
errors.no_fingerprint_returned = Дестинацијата не врати отпечаток
titles.intro = Ви го претставуваме {name}
errors.body_too_long = Вашата порака е предолга
errors.title_too_long = Вашиот наслов е предолг
errors.unknown_document = Непознат документ
errors.remote_failed = Далечинското барање не успеа
errors.service_unavailable = Услугата за поднесување привремено е недостапна. Обидете се повторно подоцна.
titles.someone = Некој

errors.invalid_id = Невалидно ID
errors.invalid_project_id = Невалидно ID на проект
errors.forum_not_found = Форумот не е пронајден
errors.forum_not_found_in_directory = Форумот не е пронајден во директориумот
errors.not_allowed_to_post = Не е дозволено објавување
errors.project_not_found = Проектот не е пронајден
errors.access_denied = Пристапот е одбиен
errors.you_own_this_project = Го поседувате овој проект
errors.unable_to_find_project_in_directory = Не може да се најде проект во директориумот
errors.remote = Оддалечениот сервер не можеше да го заврши барањето
