[labels]
app.name = Помош
errors.not_logged_in = Не сте најавени
errors.invalid_kind = Неважечки вид
errors.help_not_configured = Помошта не е конфигурирана за овој сервер
errors.body_is_required = Напишете нешто пред да испратите
errors.title_is_required = Внесете наслов на објавата
errors.no_fingerprint_returned = Дестинацијата не врати отпечаток
titles.intro = Ви го претставуваме {name}
errors.body_too_long = Вашата порака е предолга
errors.title_too_long = Вашиот наслов е предолг
titles.someone = Некој
