[labels]
app.name = സഹായം
errors.not_logged_in = ലോഗിൻ ചെയ്തിട്ടില്ല
errors.invalid_kind = അസാധുവായ തരം
errors.help_not_configured = ഈ സെർവറിനായി സഹായം കോൺഫിഗർ ചെയ്തിട്ടില്ല
errors.body_is_required = സമർപ്പിക്കുന്നതിന് മുമ്പ് എന്തെങ്കിലും ടൈപ്പ് ചെയ്യുക
errors.title_is_required = നിങ്ങളുടെ പോസ്റ്റിന് ഒരു തലക്കെട്ട് നൽകുക
errors.no_fingerprint_returned = ലക്ഷ്യസ്ഥാനം ഫിംഗർപ്രിന്റ് തിരികെ നൽകിയില്ല
titles.intro = അവതരിപ്പിക്കുന്നു {name}
errors.body_too_long = നിങ്ങളുടെ സന്ദേശം വളരെ നീളമുള്ളതാണ്
errors.title_too_long = നിങ്ങളുടെ തലക്കെട്ട് വളരെ നീളമുള്ളതാണ്
titles.someone = ആരോ
