[labels]
app.name = സഹായം
errors.not_logged_in = ലോഗിൻ ചെയ്തിട്ടില്ല
errors.invalid_kind = അസാധുവായ തരം
errors.help_not_configured = ഈ സെർവറിനായി സഹായം കോൺഫിഗർ ചെയ്തിട്ടില്ല
errors.body_is_required = സമർപ്പിക്കുന്നതിന് മുമ്പ് എന്തെങ്കിലും ടൈപ്പ് ചെയ്യുക
errors.title_is_required = നിങ്ങളുടെ പോസ്റ്റിന് ഒരു തലക്കെട്ട് നൽകുക
errors.no_fingerprint_returned = ലക്ഷ്യസ്ഥാനം ഫിംഗർപ്രിന്റ് തിരികെ നൽകിയില്ല
titles.intro = അവതരിപ്പിക്കുന്നു {name}
errors.body_too_long = നിങ്ങളുടെ സന്ദേശം വളരെ നീളമുള്ളതാണ്
errors.title_too_long = നിങ്ങളുടെ തലക്കെട്ട് വളരെ നീളമുള്ളതാണ്
errors.unknown_document = അജ്ഞാത ഡോക്യുമെന്റ്
errors.remote_failed = റിമോട്ട് അഭ്യർത്ഥന പരാജയപ്പെട്ടു
errors.service_unavailable = സമർപ്പണ സേവനം താൽക്കാലികമായി ലഭ്യമല്ല. ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക.
titles.someone = ആരോ

errors.invalid_id = അസാധുവായ ID
errors.invalid_project_id = അസാധുവായ പ്രോജക്റ്റ് ID
errors.forum_not_found = ഫോറം കണ്ടെത്തിയില്ല
errors.forum_not_found_in_directory = ഡയറക്ടറിയിൽ ഫോറം കണ്ടെത്തിയില്ല
errors.not_allowed_to_post = പോസ്റ്റ് ചെയ്യാൻ അനുവാദമില്ല
errors.project_not_found = പ്രോജക്റ്റ് കണ്ടെത്തിയില്ല
errors.access_denied = പ്രവേശനം നിരസിച്ചു
errors.you_own_this_project = നിങ്ങൾ ഈ പ്രോജക്റ്റിന്റെ ഉടമയാണ്
errors.unable_to_find_project_in_directory = ഡയറക്ടറിയിൽ പ്രോജക്റ്റ് കണ്ടെത്താൻ കഴിയില്ല
errors.remote = വിദൂര സെർവറിന് അഭ്യർത്ഥന പൂർത്തിയാക്കാൻ കഴിഞ്ഞില്ല
