[labels]
app.name = Hjelp
errors.not_logged_in = Ikke logget inn
errors.invalid_kind = Ugyldig type
errors.help_not_configured = Hjelp er ikke konfigurert for denne serveren
errors.body_is_required = Skriv noe før du sender
errors.title_is_required = Gi innlegget ditt en tittel
errors.no_fingerprint_returned = Destinasjonen returnerte ikke et fingeravtrykk
titles.intro = Vi presenterer {name}
errors.body_too_long = Meldingen din er for lang
errors.title_too_long = Tittelen din er for lang
errors.unknown_document = Ukjent dokument
errors.remote_failed = Ekstern forespørsel mislyktes
errors.service_unavailable = Innsendingstjenesten er midlertidig utilgjengelig. Prøv igjen senere.
titles.someone = Noen

errors.invalid_id = Ugyldig ID
errors.invalid_project_id = Ugyldig prosjekt-ID
errors.forum_not_found = Forum ikke funnet
errors.forum_not_found_in_directory = Forumet ble ikke funnet i katalogen
errors.not_allowed_to_post = Ikke tillatt å poste
errors.project_not_found = Prosjekt ikke funnet
errors.access_denied = Tilgang nektet
errors.you_own_this_project = Du eier dette prosjektet
errors.unable_to_find_project_in_directory = Kan ikke finne prosjekt i katalogen
errors.remote = Den eksterne serveren kunne ikke fullføre forespørselen
