[labels]
app.name = मद्दत
errors.not_logged_in = लग इन गरिएको छैन
errors.invalid_kind = अमान्य प्रकार
errors.help_not_configured = यो सर्भरका लागि सहायता कन्फिगर गरिएको छैन
errors.body_is_required = कृपया पेश गर्नु अघि केही टाइप गर्नुहोस्
errors.title_is_required = कृपया आफ्नो पोस्टलाई एउटा शीर्षक दिनुहोस्
errors.no_fingerprint_returned = गन्तव्यले फिङ्गरप्रिन्ट फिर्ता गरेन
titles.intro = प्रस्तुत छ {name}
errors.body_too_long = तपाईंको सन्देश धेरै लामो छ
errors.title_too_long = तपाईंको शीर्षक धेरै लामो छ
errors.unknown_document = अज्ञात कागजात
errors.remote_failed = टाढाको अनुरोध असफल भयो
errors.service_unavailable = पेस गर्ने सेवा अस्थायी रूपमा उपलब्ध छैन। कृपया पछि फेरि प्रयास गर्नुहोस्।
titles.someone = कोही

errors.invalid_id = अमान्य ID
errors.invalid_project_id = अमान्य परियोजना ID
errors.forum_not_found = फोरम फेला परेन
errors.forum_not_found_in_directory = डाइरेक्टरीमा फोरम फेला परेन
errors.not_allowed_to_post = पोस्ट गर्न अनुमति छैन
errors.project_not_found = परियोजना फेला परेन
errors.access_denied = पहुँच अस्वीकृत
errors.you_own_this_project = यो परियोजना तपाईंको हो
errors.unable_to_find_project_in_directory = डाइरेक्टरीमा रिपोजिटोरी फेला पार्न असमर्थ। कृपया रिपोजिटोरी URL प्रदान गर्नुहोस्।
errors.remote = टाढाको सर्भरले अनुरोध पूरा गर्न सकेन
