[labels]
app.name = Gargaarsa
errors.not_logged_in = Hin seenne
errors.invalid_kind = Gosa hin sirrii
errors.help_not_configured = Gargaarsi sarvarii kanaaf qophaa'aa miti
errors.body_is_required = Maaloo erguu dura waan tokko barreessi
errors.title_is_required = Maaloo barruu kee mata-duree itti kenni
errors.no_fingerprint_returned = Bakki dhaqaatu mallattoo quba hin deebifne
titles.intro = {name} si beeksisuu
errors.body_too_long = Ergaan kee baayʼee dheeraadha
errors.title_too_long = Mata duree kee baayʼee dheeraadha
titles.someone = Namni tokko
