[labels]
app.name = Pomoc
errors.not_logged_in = Niezalogowany
errors.invalid_kind = Nieprawidłowy typ
errors.help_not_configured = Pomoc nie jest skonfigurowana dla tego serwera
errors.body_is_required = Wpisz coś przed wysłaniem
errors.title_is_required = Nadaj swojemu wpisowi tytuł
errors.no_fingerprint_returned = Cel nie zwrócił odcisku
titles.intro = Przedstawiamy {name}
errors.body_too_long = Twoja wiadomość jest za długa
errors.title_too_long = Twój tytuł jest za długi
errors.unknown_document = Nieznany dokument
errors.remote_failed = Żądanie zdalne nie powiodło się
errors.service_unavailable = Usługa przesyłania jest tymczasowo niedostępna. Spróbuj ponownie później.
titles.someone = Ktoś

errors.invalid_id = Nieprawidłowe ID
errors.invalid_project_id = Nieprawidłowe ID projektu
errors.forum_not_found = Nie znaleziono forum
errors.forum_not_found_in_directory = Nie znaleziono forum w katalogu
errors.not_allowed_to_post = Nie można publikować
errors.project_not_found = Nie znaleziono projektu
errors.access_denied = Brak dostępu
errors.you_own_this_project = Jesteś właścicielem tego projektu
errors.unable_to_find_project_in_directory = Nie można znaleźć projektu w katalogu
errors.remote = Zdalny serwer nie mógł zrealizować żądania
