[labels]
app.name = Pomoc
errors.not_logged_in = Niezalogowany
errors.invalid_kind = Nieprawidłowy typ
errors.help_not_configured = Pomoc nie jest skonfigurowana dla tego serwera
errors.body_is_required = Wpisz coś przed wysłaniem
errors.title_is_required = Nadaj swojemu wpisowi tytuł
errors.no_fingerprint_returned = Cel nie zwrócił odcisku
titles.intro = Przedstawiamy {name}
errors.body_too_long = Twoja wiadomość jest za długa
errors.title_too_long = Twój tytuł jest za długi
titles.someone = Ktoś
