[labels]
app.name = Yanapay
errors.not_logged_in = Mana yaykusqachu
errors.invalid_kind = Mana allin laya
errors.help_not_configured = Kay servidorpaq yanapay mana wakichasqachu
errors.body_is_required = Apachiy ñawpaq imallatapas qillqaykuy
errors.title_is_required = Qillqasqaykiman huk sutita churay
errors.no_fingerprint_returned = Chayanan kitimanta mana ruk'ana unanchaytachu kutichirqan
titles.intro = {name} riqsichiyku
errors.body_too_long = Willakuyniyki ancha suni
errors.title_too_long = Sutiyki ancha suni
titles.someone = Pipas
