[labels]
app.name = Yanapay
errors.invalid_kind = Mana allin laya
errors.help_not_configured = Kay servidorpaq yanapay mana wakichasqachu
errors.body_is_required = Ama hina kaspa, manaraq apachispa aswan willakuykunata yapay
errors.title_is_required = Qillqaykiman huk sutinchayta churay
errors.no_fingerprint_returned = Destinoqa mana ruk'ana unanchata kutichirqanchu
titles.intro = {name} riqsichiyku
errors.body_too_long = Willakuyniyki nishu suni
errors.title_too_long = Sutinchayniyki nishu suni
errors.unknown_document = Mana riqsisqa documento
errors.remote_failed = Karu mañakuy mana atikurqachu
errors.service_unavailable = Apachina servicioqa kunanqa mana kanchu. Qhipaman kutimanta ruway.
titles.someone = Huk runa

errors.invalid_id = Mana allin ID
errors.invalid_project_id = Mana allin proyecto ID
errors.forum_not_found = Foro mana tarisqachu
errors.forum_not_found_in_directory = Directoriopi foro mana tarisqachu
errors.not_allowed_to_post = Qillqay mana saqisqachu
errors.project_not_found = Proyecto mana tarisqachu
errors.access_denied = Yaykuy mana saqisqachu
errors.unable_to_find_project_in_directory = Directoriopi proyecto mana tariy atikurqachu
errors.remote = Karu servidorqa mañakuyta manam tukuyta atirqachu

errors.unable_to_connect_to_server = Servidorman mana t'inkiy atikurqanchu
errors.could_not_reach_project_owner = Proyecto apuqman mana chayayta atikurqanchu
errors.no_object_returned = Proyectopa apuqninqa mana musuq itemta kutichirqanchu
errors.invalid_post_id = Mana allin qillqa ID
errors.invalid_title = Mana allin sutinchay
errors.invalid_body = Mana allin qillqa
