[labels]
app.name = Ajutor
errors.not_logged_in = Neautentificat
errors.invalid_kind = Tip nevalid
errors.help_not_configured = Ajutorul nu este configurat pentru acest server
errors.body_is_required = Scrie ceva înainte de a trimite
errors.title_is_required = Adaugă un titlu postării tale
errors.no_fingerprint_returned = Destinația nu a returnat o amprentă
titles.intro = Vă prezentăm {name}
errors.body_too_long = Mesajul tău este prea lung
errors.title_too_long = Titlul tău este prea lung
errors.unknown_document = Document necunoscut
errors.remote_failed = Cererea la distanță a eșuat
errors.service_unavailable = Serviciul de trimitere este temporar indisponibil. Vă rugăm să încercați din nou mai târziu.
titles.someone = Cineva

errors.invalid_id = ID invalid
errors.invalid_project_id = ID proiect invalid
errors.forum_not_found = Forumul nu a fost găsit
errors.forum_not_found_in_directory = Forumul nu a fost găsit în director
errors.not_allowed_to_post = Nu ai permisiunea de a posta
errors.project_not_found = Proiectul nu a fost găsit
errors.access_denied = Acces refuzat
errors.you_own_this_project = Deții acest proiect
errors.unable_to_find_project_in_directory = Proiectul nu a fost găsit în director
errors.remote = Serverul la distanță nu a putut finaliza cererea
