[labels]
app.name = උදව්
errors.not_logged_in = ලොග් වී නැත
errors.invalid_kind = අවලංගු වර්ගය
errors.help_not_configured = මෙම සේවාදායකය සඳහා උදව් වින්‍යාස කර නොමැත
errors.body_is_required = කරුණාකර ඉදිරිපත් කිරීමට පෙර යමක් ටයිප් කරන්න
errors.title_is_required = කරුණාකර ඔබේ පළ කිරීමට මාතෘකාවක් දෙන්න
errors.no_fingerprint_returned = ගමනාන්තය ඇඟිලි සලකුණක් ආපසු එව්වේ නැත
titles.intro = හඳුන්වා දෙමින් {name}
errors.body_too_long = ඔබේ පණිවිඩය දිගට වැඩියි
errors.title_too_long = ඔබේ මාතෘකාව දිගට වැඩියි
titles.someone = කවුරුහරි
