[labels]
app.name = Pomocník
errors.not_logged_in = Nie ste prihlásený
errors.invalid_kind = Neplatný typ
errors.help_not_configured = Pomocník nie je pre tento server nakonfigurovaný
errors.body_is_required = Pred odoslaním niečo napíšte
errors.title_is_required = Zadajte názov príspevku
errors.no_fingerprint_returned = Cieľ nevrátil odtlačok
titles.intro = Predstavujeme {name}
errors.body_too_long = Vaša správa je príliš dlhá
errors.title_too_long = Váš názov je príliš dlhý
errors.unknown_document = Neznámy dokument
errors.remote_failed = Vzdialená požiadavka zlyhala
errors.service_unavailable = Služba na odosielanie je dočasne nedostupná. Skúste to znova neskôr.
titles.someone = Niekto

errors.invalid_id = Neplatné ID
errors.invalid_project_id = Neplatné ID projektu
errors.forum_not_found = Fórum sa nenašlo
errors.forum_not_found_in_directory = Fórum sa v adresári nenašlo
errors.not_allowed_to_post = Nepovolené pridávať príspevky
errors.project_not_found = Projekt sa nenašiel
errors.access_denied = Prístup zamietnutý
errors.you_own_this_project = Tento projekt vlastníte
errors.unable_to_find_project_in_directory = Projekt sa nepodarilo nájsť v adresári
errors.remote = Vzdialený server nemohol dokončiť požiadavku
