[labels]
app.name = Pomocník
errors.not_logged_in = Nie ste prihlásený
errors.invalid_kind = Neplatný typ
errors.help_not_configured = Pomocník nie je pre tento server nakonfigurovaný
errors.body_is_required = Pred odoslaním niečo napíšte
errors.title_is_required = Zadajte názov príspevku
errors.no_fingerprint_returned = Cieľ nevrátil odtlačok
titles.intro = Predstavujeme {name}
errors.body_too_long = Vaša správa je príliš dlhá
errors.title_too_long = Váš názov je príliš dlhý
errors.unknown_document = Neznámy dokument
errors.remote_failed = Vzdialená požiadavka zlyhala
titles.someone = Niekto
