[labels]
app.name = Pomoč
errors.not_logged_in = Niste prijavljeni
errors.invalid_kind = Neveljavna vrsta
errors.help_not_configured = Pomoč za ta strežnik ni nastavljena
errors.body_is_required = Pred pošiljanjem nekaj napišite
errors.title_is_required = Vnesite naslov objave
errors.no_fingerprint_returned = Cilj ni vrnil prstnega odtisa
titles.intro = Predstavljamo {name}
titles.question = Vprašanje od {name}
errors.body_too_long = Vaše sporočilo je predolgo
errors.title_too_long = Vaš naslov je predolg
titles.someone = Nekdo
