[labels]
app.name = Ndihmë
errors.not_logged_in = Nuk jeni i kyçur
errors.invalid_kind = Lloj i pavlefshëm
errors.help_not_configured = Ndihma nuk është konfiguruar për këtë server
errors.body_is_required = Shkruani diçka para se ta dërgoni
errors.title_is_required = Vendosni një titull për postimin
errors.no_fingerprint_returned = Destinacioni nuk ktheu një gjurmë
titles.intro = Ju prezantojmë {name}
errors.body_too_long = Mesazhi juaj është shumë i gjatë
errors.title_too_long = Titulli juaj është shumë i gjatë
errors.unknown_document = Dokument i panjohur
errors.remote_failed = Kërkesa në distancë dështoi
errors.service_unavailable = Shërbimi i dorëzimit është përkohësisht i padisponueshëm. Ju lutemi provoni përsëri më vonë.
titles.someone = Dikush

errors.invalid_id = ID e pavlefshme
errors.invalid_project_id = ID e projektit e pavlefshme
errors.forum_not_found = Forumi nuk u gjet
errors.forum_not_found_in_directory = Forumi nuk u gjet në direktori
errors.not_allowed_to_post = Nuk lejohet të postoni
errors.project_not_found = Projekti nuk u gjet
errors.access_denied = Qasja u refuzua
errors.you_own_this_project = Ju zotëroni këtë projekt
errors.unable_to_find_project_in_directory = Projekti nuk u gjet në direktori
errors.remote = Serveri i largët nuk mundi ta përfundonte kërkesën
