[labels]
app.name = Ndihmë
errors.not_logged_in = Nuk jeni i kyçur
errors.invalid_kind = Lloj i pavlefshëm
errors.help_not_configured = Ndihma nuk është konfiguruar për këtë server
errors.body_is_required = Shkruani diçka para se ta dërgoni
errors.title_is_required = Vendosni një titull për postimin
errors.no_fingerprint_returned = Destinacioni nuk ktheu një gjurmë
titles.intro = Ju prezantojmë {name}
titles.question = Një pyetje nga {name}
errors.body_too_long = Mesazhi juaj është shumë i gjatë
errors.title_too_long = Titulli juaj është shumë i gjatë
titles.someone = Dikush
