[labels]
app.name = Помоћ
errors.not_logged_in = Нисте пријављени
errors.invalid_kind = Неважећа врста
errors.help_not_configured = Помоћ није подешена за овај сервер
errors.body_is_required = Унесите нешто пре слања
errors.title_is_required = Унесите наслов објаве
errors.no_fingerprint_returned = Одредиште није вратило отисак
titles.intro = Представљамо {name}
errors.body_too_long = Ваша порука је предугачка
errors.title_too_long = Ваш наслов је предугачак
errors.unknown_document = Непознат документ
errors.remote_failed = Удаљени захтев није успео
errors.service_unavailable = Услуга за слање је тренутно недоступна. Покушајте поново касније.
titles.someone = Неко

errors.invalid_id = Неисправан ID
errors.invalid_project_id = Неисправан ID пројекта
errors.forum_not_found = Форум није пронађен
errors.forum_not_found_in_directory = Форум није пронађен у директоријуму
errors.not_allowed_to_post = Постављање није дозвољено
errors.project_not_found = Пројекат није пронађен
errors.access_denied = Приступ одбијен
errors.you_own_this_project = Поседујете овај пројекат
errors.unable_to_find_project_in_directory = Пројекат није могуће пронаћи у директоријуму
errors.remote = Удаљени сервер није могао да заврши захтев
