[labels]
app.name = Помоћ
errors.not_logged_in = Нисте пријављени
errors.invalid_kind = Неважећа врста
errors.help_not_configured = Помоћ није подешена за овај сервер
errors.body_is_required = Унесите нешто пре слања
errors.title_is_required = Унесите наслов објаве
errors.no_fingerprint_returned = Одредиште није вратило отисак
titles.intro = Представљамо {name}
titles.question = Питање од {name}
errors.body_too_long = Ваша порука је предугачка
errors.title_too_long = Ваш наслов је предугачак
titles.someone = Неко
