[labels]
app.name = Bantosan
errors.not_logged_in = Tacan asup
errors.invalid_kind = Jenis henteu sah
errors.help_not_configured = Pitulung tacan dikonfigurasi pikeun server ieu
errors.body_is_required = Mangga ketik hiji hal saméméh ngirim
errors.title_is_required = Mangga pasihan judul kana kintunan anjeun
errors.no_fingerprint_returned = Tujuan henteu mulangkeun sidik ramo
titles.intro = Ngenalkeun {name}
errors.body_too_long = Pesen anjeun panjang teuing
errors.title_too_long = Judul anjeun panjang teuing
errors.unknown_document = Dokumén teu dikenal
errors.remote_failed = Pamundut jauh gagal
errors.service_unavailable = Layanan ngirim samentawis teu sayagi. Mangga cobian deui engké.
titles.someone = Saurang

errors.invalid_id = ID teu sah
errors.invalid_project_id = ID proyék teu sah
errors.forum_not_found = Forum teu kapanggih
errors.forum_not_found_in_directory = Forum teu kapanggih dina diréktori
errors.not_allowed_to_post = Teu diidinan ngirim pos
errors.project_not_found = Proyék teu kapanggih
errors.access_denied = Aksés ditolak
errors.you_own_this_project = Anjeun nu boga proyék ieu
errors.unable_to_find_project_in_directory = Teu bisa nyatemukeun proyék dina diréktori
errors.remote = Server jauh teu tiasa ngaréngsékeun paménta
