[labels]
app.name = Hjälp
errors.not_logged_in = Inte inloggad
errors.invalid_kind = Ogiltig typ
errors.help_not_configured = Hjälp är inte konfigurerad för den här servern
errors.body_is_required = Skriv något innan du skickar
errors.title_is_required = Ge ditt inlägg en rubrik
errors.no_fingerprint_returned = Destinationen returnerade inget fingeravtryck
titles.intro = Vi presenterar {name}
errors.body_too_long = Ditt meddelande är för långt
errors.title_too_long = Din titel är för lång
titles.someone = Någon
