[labels]
app.name = Msaada
errors.not_logged_in = Hujaingia
errors.invalid_kind = Aina batili
errors.help_not_configured = Msaada haujasanidiwa kwa seva hii
errors.body_is_required = Tafadhali andika kitu kabla ya kuwasilisha
errors.title_is_required = Tafadhali ipe chapisho lako kichwa
errors.no_fingerprint_returned = Mahali pa kufikia hapakurudisha alama ya kidole
titles.intro = Tunakutambulisha kwa {name}
errors.body_too_long = Ujumbe wako ni mrefu sana
errors.title_too_long = Kichwa chako ni kirefu sana
titles.someone = Mtu fulani
