[labels]
app.name = సహాయం
errors.not_logged_in = లాగిన్ కాలేదు
errors.invalid_kind = చెల్లని రకం
errors.help_not_configured = ఈ సర్వర్‌కు సహాయం కాన్ఫిగర్ చేయబడలేదు
errors.body_is_required = దయచేసి సమర్పించే ముందు ఏదైనా టైప్ చేయండి
errors.title_is_required = దయచేసి మీ పోస్ట్‌కు శీర్షికను ఇవ్వండి
errors.no_fingerprint_returned = గమ్యస్థానం వేలిముద్రను తిరిగి ఇవ్వలేదు
titles.intro = పరిచయం {name}
errors.body_too_long = మీ సందేశం చాలా పొడవుగా ఉంది
errors.title_too_long = మీ శీర్షిక చాలా పొడవుగా ఉంది
errors.unknown_document = తెలియని పత్రం
errors.remote_failed = రిమోట్ అభ్యర్థన విఫలమైంది
errors.service_unavailable = సమర్పణ సేవ తాత్కాలికంగా అందుబాటులో లేదు. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి.
titles.someone = ఎవరో

errors.invalid_id = చెల్లని ID
errors.invalid_project_id = చెల్లని ప్రాజెక్ట్ ID
errors.forum_not_found = ఫోరమ్ కనుగొనబడలేదు
errors.forum_not_found_in_directory = డైరెక్టరీలో ఫోరమ్ కనుగొనబడలేదు
errors.not_allowed_to_post = పోస్ట్ చేయడానికి అనుమతించబడలేదు
errors.project_not_found = ప్రాజెక్ట్ కనుగొనబడలేదు
errors.access_denied = యాక్సెస్ తిరస్కరించబడింది
errors.you_own_this_project = ఈ ప్రాజెక్ట్ మీది
errors.unable_to_find_project_in_directory = డైరెక్టరీలో ప్రాజెక్ట్‌ను కనుగొనడం సాధ్యం కాలేదు
errors.remote = రిమోట్ సర్వర్ అభ్యర్థనను పూర్తి చేయలేకపోయింది
