[labels]
app.name = Кӯмак
errors.not_logged_in = Ворид нашудаед
errors.invalid_kind = Навъи нодуруст
errors.help_not_configured = Кӯмак барои ин сервер танзим нашудааст
errors.body_is_required = Лутфан пеш аз фиристодан чизе нависед
errors.title_is_required = Лутфан ба паёми худ сарлавҳа диҳед
errors.no_fingerprint_returned = Мақсад нақши ангуштро барнагардонид
titles.intro = Шиносоӣ бо {name}
errors.body_too_long = Паёми шумо хеле дароз аст
errors.title_too_long = Сарлавҳаи шумо хеле дароз аст
errors.unknown_document = Ҳуҷҷати номаълум
errors.remote_failed = Дархости дурдаст ноком шуд
errors.service_unavailable = Хадамоти ирсол муваққатан дастрас нест. Лутфан баъдтар бори дигар кӯшиш кунед.
titles.someone = Касе

errors.invalid_id = ID нодуруст аст
errors.invalid_project_id = ID-и лоиҳа нодуруст аст
errors.forum_not_found = Форум ёфт нашуд
errors.forum_not_found_in_directory = Форум дар феҳрист ёфт нашуд
errors.not_allowed_to_post = Иҷозати фиристодан нест
errors.project_not_found = Лоиҳа ёфт нашуд
errors.access_denied = Дастрасӣ манъ аст
errors.you_own_this_project = Шумо соҳиби ин лоиҳа ҳастед
errors.unable_to_find_project_in_directory = Ёфтани лоиҳа дар феҳрист имконнопазир аст
errors.remote = Сервери дурдаст дархостро иҷро карда натавонист
