[labels]
app.name = Кӯмак
errors.not_logged_in = Ворид нашудаед
errors.invalid_kind = Навъи нодуруст
errors.help_not_configured = Кӯмак барои ин сервер танзим нашудааст
errors.body_is_required = Лутфан пеш аз фиристодан чизе нависед
errors.title_is_required = Лутфан ба паёми худ сарлавҳа диҳед
errors.no_fingerprint_returned = Мақсад нақши ангуштро барнагардонид
titles.intro = Шиносоӣ бо {name}
titles.question = Савол аз {name}
errors.body_too_long = Паёми шумо хеле дароз аст
errors.title_too_long = Сарлавҳаи шумо хеле дароз аст
titles.someone = Касе
