[labels]
app.name = Tulong
errors.not_logged_in = Hindi naka-log in
errors.invalid_kind = Hindi wastong uri
errors.help_not_configured = Hindi pa naka-configure ang tulong para sa server na ito
errors.body_is_required = Mangyaring mag-type ng kahit ano bago isumite
errors.title_is_required = Mangyaring bigyan ng pamagat ang iyong post
errors.no_fingerprint_returned = Hindi nagbalik ng fingerprint ang patutunguhan
titles.intro = Ipinakikilala si {name}
errors.body_too_long = Masyadong mahaba ang iyong mensahe
errors.title_too_long = Masyadong mahaba ang iyong pamagat
errors.unknown_document = Hindi kilalang document
errors.remote_failed = Nabigo ang malayong kahilingan
errors.service_unavailable = Pansamantalang hindi available ang serbisyo sa pagsusumite. Pakisubukang muli mamaya.
titles.someone = Isang tao

errors.invalid_id = Hindi valid ang ID
errors.invalid_project_id = Hindi valid ang project ID
errors.forum_not_found = Hindi nakita ang forum
errors.forum_not_found_in_directory = Hindi nakita ang forum sa directory
errors.not_allowed_to_post = Hindi pinapayagang mag-post
errors.project_not_found = Hindi nakita ang project
errors.access_denied = Hindi pinapayagan
errors.you_own_this_project = Pag-aari mo ang project na ito
errors.unable_to_find_project_in_directory = Hindi mahanap ang project sa directory
errors.remote = Hindi makumpleto ng malayong server ang kahilingan
