[labels]
app.name = Tulong
errors.not_logged_in = Hindi naka-log in
errors.invalid_kind = Hindi wastong uri
errors.help_not_configured = Hindi pa naka-configure ang tulong para sa server na ito
errors.body_is_required = Mangyaring mag-type ng kahit ano bago isumite
errors.title_is_required = Mangyaring bigyan ng pamagat ang iyong post
errors.no_fingerprint_returned = Hindi nagbalik ng fingerprint ang patutunguhan
titles.intro = Ipinakikilala si {name}
errors.body_too_long = Masyadong mahaba ang iyong mensahe
errors.title_too_long = Masyadong mahaba ang iyong pamagat
errors.unknown_document = Hindi kilalang document
errors.remote_failed = Nabigo ang malayong kahilingan
titles.someone = Isang tao
