[labels]
app.name = مدد
errors.not_logged_in = لاگ ان نہیں ہیں
errors.invalid_kind = غلط قسم
errors.help_not_configured = اس سرور کے لیے مدد ترتیب نہیں دی گئی
errors.body_is_required = براہ کرم جمع کرنے سے پہلے کچھ لکھیں
errors.title_is_required = براہ کرم اپنی پوسٹ کو ایک عنوان دیں
errors.no_fingerprint_returned = منزل نے فنگر پرنٹ واپس نہیں کیا
titles.intro = پیش ہے {name}
errors.body_too_long = آپ کا پیغام بہت طویل ہے
errors.title_too_long = آپ کا عنوان بہت طویل ہے
errors.unknown_document = نامعلوم دستاویز
errors.remote_failed = ریموٹ درخواست ناکام ہوگئی
errors.service_unavailable = جمع کرانے کی سروس عارضی طور پر دستیاب نہیں ہے۔ براہ کرم بعد میں دوبارہ کوشش کریں۔
titles.someone = کوئی

errors.invalid_id = غلط ID
errors.invalid_project_id = غلط پروجیکٹ ID
errors.forum_not_found = فورم نہیں ملا
errors.forum_not_found_in_directory = ڈائریکٹری میں فورم نہیں ملا
errors.not_allowed_to_post = پوسٹ کرنے کی اجازت نہیں
errors.project_not_found = پروجیکٹ نہیں ملا
errors.access_denied = رسائی مسترد
errors.you_own_this_project = آپ اس پروجیکٹ کے مالک ہیں
errors.unable_to_find_project_in_directory = ڈائریکٹری میں پروجیکٹ ڈھونڈنے سے قاصر
errors.remote = ریموٹ سرور درخواست مکمل نہیں کر سکا
