[labels]
app.name = مدد
errors.not_logged_in = لاگ ان نہیں ہیں
errors.invalid_kind = غلط قسم
errors.help_not_configured = اس سرور کے لیے مدد ترتیب نہیں دی گئی
errors.body_is_required = براہ کرم جمع کرنے سے پہلے کچھ لکھیں
errors.title_is_required = براہ کرم اپنی پوسٹ کو ایک عنوان دیں
errors.no_fingerprint_returned = منزل نے فنگر پرنٹ واپس نہیں کیا
titles.intro = پیش ہے {name}
errors.body_too_long = آپ کا پیغام بہت طویل ہے
errors.title_too_long = آپ کا عنوان بہت طویل ہے
titles.someone = کوئی
