[labels]
app.name = Yordam
errors.not_logged_in = Tizimga kirilmagan
errors.invalid_kind = Notoʻgʻri tur
errors.help_not_configured = Ushbu server uchun yordam sozlanmagan
errors.body_is_required = Yuborishdan oldin biror narsa yozing
errors.title_is_required = Postingizga sarlavha bering
errors.no_fingerprint_returned = Manzil barmoq izini qaytarmadi
titles.intro = {name} bilan tanishing
errors.body_too_long = Xabaringiz juda uzun
errors.title_too_long = Sarlavhangiz juda uzun
errors.unknown_document = Noma’lum hujjat
errors.remote_failed = Masofaviy soʻrov bajarilmadi
errors.service_unavailable = Yuborish xizmati vaqtincha mavjud emas. Iltimos, keyinroq qayta urinib koʻring.
titles.someone = Kimdir

errors.invalid_id = Noto‘g‘ri ID
errors.invalid_project_id = Noto‘g‘ri loyiha ID
errors.forum_not_found = Forum topilmadi
errors.forum_not_found_in_directory = Forum katalogda topilmadi
errors.not_allowed_to_post = Post qoldirishga ruxsat yo‘q
errors.project_not_found = Loyiha topilmadi
errors.access_denied = Ruxsat berilmadi
errors.you_own_this_project = Siz bu loyiha egasisiz
errors.unable_to_find_project_in_directory = Katalogda loyiha topilmadi
errors.remote = Masofadagi server so'rovni yakunlay olmadi
