[labels]
app.name = Uncedo
errors.not_logged_in = Awungenanga
errors.invalid_kind = Uhlobo olungasebenziyo
errors.help_not_configured = Uncedo alusetelwanga kule seva
errors.body_is_required = Nceda ubhale okuthile phambi kokungenisa
errors.title_is_required = Nceda nika iposti yakho isihloko
errors.no_fingerprint_returned = Indawo ekuyiwa kuyo ayibuyisanga umnwe
titles.intro = Sazisa u-{name}
errors.body_too_long = Umyalezo wakho mude kakhulu
errors.title_too_long = Isihloko sakho side kakhulu
titles.someone = Umntu
