[labels]
app.name = הילף
errors.not_logged_in = נישט אײַנגעלאָגט
errors.invalid_kind = אומגילטיקער טיפּ
errors.help_not_configured = הילף איז נישט קאָנפֿיגורירט פֿאַר דעם סערווער
errors.body_is_required = ביטע שרײַבט עפּעס פֿאַרן אַרײַנשיקן
errors.title_is_required = ביטע גיט אײַער פּאָסטונג אַ קעפּל
errors.no_fingerprint_returned = די דעסטינאַציע האָט נישט צוריקגעגעבן קיין פֿינגעראָפּדרוק
titles.intro = פֿירט אײַך פֿאָר {name}
errors.body_too_long = אייער מעלדונג איז צו לאַנג
errors.title_too_long = אייער טיטל איז צו לאַנג
errors.unknown_document = אומבאַקאַנטער דאָקומענט
errors.remote_failed = ווייטע אנפרעג איז דורכגעפאלן
errors.service_unavailable = דער אַרײַנגעב־דינסט איז צײַטווײַליק נישט צוטריטלעך. ביטע פּרּווט נאָך אַ מאָל שפּעטער.
titles.someone = עמעצער

errors.invalid_id = אומגילטיקער ID
errors.invalid_project_id = אומגילטיקער פּראָיעקט ID
errors.forum_not_found = פֿאָרום נישט געפֿונען
errors.forum_not_found_in_directory = פֿאָרום נישט געפֿונען אין דירעקטאָריע
errors.not_allowed_to_post = נישט דערלויבט צו פּאָסטן
errors.project_not_found = פּראָיעקט נישט געפֿונען
errors.access_denied = צוטריט פֿאַרווערט
errors.you_own_this_project = איר באַזיצט דעם פּראָיעקט
errors.unable_to_find_project_in_directory = נישט מעגלעך צו געפֿינען פּראָיעקט אין דירעקטאָריע
errors.remote = דער ווײַטער סערווער האָט נישט געקענט פֿאַרענדיקן די בקשה
