[labels]
app.name = הילף
errors.not_logged_in = נישט אײַנגעלאָגט
errors.invalid_kind = אומגילטיקער טיפּ
errors.help_not_configured = הילף איז נישט קאָנפֿיגורירט פֿאַר דעם סערווער
errors.body_is_required = ביטע שרײַבט עפּעס פֿאַרן אַרײַנשיקן
errors.title_is_required = ביטע גיט אײַער פּאָסטונג אַ קעפּל
errors.no_fingerprint_returned = די דעסטינאַציע האָט נישט צוריקגעגעבן קיין פֿינגעראָפּדרוק
titles.intro = פֿירט אײַך פֿאָר {name}
errors.body_too_long = אייער מעלדונג איז צו לאַנג
errors.title_too_long = אייער טיטל איז צו לאַנג
titles.someone = עמעצער
