[labels]
app.name = Ìrànlọ́wọ́
errors.not_logged_in = Kò wọlé
errors.invalid_kind = Irúfẹ́ tí kò tọ́
errors.help_not_configured = A kò ṣètò Ìrànlọ́wọ́ fún olúwaaṣẹ yìí
errors.body_is_required = Jọ̀wọ́ kọ ohun kan kí o tó fi ránṣẹ́
errors.title_is_required = Jọ̀wọ́ fún ìfìwéránṣẹ́ rẹ ní àkòrí
errors.no_fingerprint_returned = Ibi tí a fi ránṣẹ́ sí kò dá ìka-ìtẹ̀ padà
titles.intro = Ní fífi {name} hàn
titles.question = Ìbéèrè kan láti ọ̀dọ̀ {name}
errors.body_too_long = Ifiranṣẹ rẹ gun ju
errors.title_too_long = Akọle rẹ gun ju
titles.someone = Ẹnikan
