[labels]
app.name = 帮助
errors.not_logged_in = 未登录
errors.invalid_kind = 类型无效
errors.help_not_configured = 此服务器尚未配置帮助
errors.body_is_required = 请先输入内容再提交
errors.title_is_required = 请为您的帖子添加标题
errors.no_fingerprint_returned = 目标未返回指纹
titles.intro = 介绍 {name}
errors.body_too_long = 你的消息太长了
errors.title_too_long = 你的标题太长了
titles.someone = 某人
