[labels]
app.name = 帮助
errors.not_logged_in = 未登录
errors.invalid_kind = 类型无效
errors.help_not_configured = 此服务器尚未配置帮助
errors.body_is_required = 请先输入内容再提交
errors.title_is_required = 请为您的帖子添加标题
errors.no_fingerprint_returned = 目标未返回指纹
titles.intro = 介绍 {name}
errors.body_too_long = 你的消息太长了
errors.title_too_long = 你的标题太长了
errors.unknown_document = 未知文档
errors.remote_failed = 远程请求失败
errors.service_unavailable = 提交服务暂时不可用。请稍后重试。
titles.someone = 某人

errors.invalid_id = ID 无效
errors.invalid_project_id = 项目 ID 无效
errors.forum_not_found = 未找到论坛
errors.forum_not_found_in_directory = 目录中未找到论坛
errors.not_allowed_to_post = 不允许发帖
errors.project_not_found = 未找到项目
errors.access_denied = 访问被拒绝
errors.you_own_this_project = 你拥有此项目
errors.unable_to_find_project_in_directory = 目录中找不到项目
errors.remote = 远程服务器无法完成请求
