[labels]
app.name = Usizo
errors.not_logged_in = Awungenile
errors.invalid_kind = Uhlobo olungavumelekile
errors.help_not_configured = Usizo alulungiselelwanga le seva
errors.body_is_required = Sicela ubhale okuthile ngaphambi kokuthumela
errors.title_is_required = Sicela unike umbhalo wakho isihloko
errors.no_fingerprint_returned = Indawo ohamba kuyo ayibuyiselanga uphawu lomunwe
titles.intro = Sazisa u-{name}
errors.body_too_long = Umyalezo wakho mude kakhulu
errors.title_too_long = Isihloko sakho side kakhulu
errors.unknown_document = Idokhumenti engaziwa
errors.remote_failed = Isicelo sesilawuli kude sihlulekile
errors.service_unavailable = Insiza yokuthumela ayitholakali okwesikhashana. Sicela uzame futhi kamuva.
titles.someone = Umuntu

errors.invalid_id = I-ID engavumelekile
errors.invalid_project_id = I-ID yephrojekthi engavumelekile
errors.forum_not_found = Iforamu ayitholakali
errors.forum_not_found_in_directory = Iforamu ayitholakali kuhlukezi
errors.not_allowed_to_post = Akuvunyelwe ukuthumela
errors.project_not_found = Iphrojekthi ayitholakali
errors.access_denied = Ukufinyelela kunqatshelwe
errors.you_own_this_project = Le phrojekthi ingeyakho
errors.unable_to_find_project_in_directory = Akukwazeki ukuthola iphrojekthi kuhlukezi
errors.remote = Iseva ekude ayikwazanga ukuqedela isicelo
