[labels]
app.name = Usizo
errors.not_logged_in = Awungenile
errors.invalid_kind = Uhlobo olungavumelekile
errors.help_not_configured = Usizo alulungiselelwanga le seva
errors.body_is_required = Sicela ubhale okuthile ngaphambi kokuthumela
errors.title_is_required = Sicela unike umbhalo wakho isihloko
errors.no_fingerprint_returned = Indawo ohamba kuyo ayibuyiselanga uphawu lomunwe
titles.intro = Sazisa u-{name}
errors.body_too_long = Umyalezo wakho mude kakhulu
errors.title_too_long = Isihloko sakho side kakhulu
titles.someone = Umuntu
