/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDocumentPrivacyRouteImport } from './routes/_authenticated/document/privacy'
import { Route as AuthenticatedDocumentRulesRouteImport } from './routes/_authenticated/document/rules'
import { Route as AuthenticatedDocumentTermsRouteImport } from './routes/_authenticated/document/terms'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentPrivacyRoute =
  AuthenticatedDocumentPrivacyRouteImport.update({
    id: '/document/privacy',
    path: '/document/privacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentRulesRoute =
  AuthenticatedDocumentRulesRouteImport.update({
    id: '/document/rules',
    path: '/document/rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentTermsRoute =
  AuthenticatedDocumentTermsRouteImport.update({
    id: '/document/terms',
    path: '/document/terms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/document/terms': typeof AuthenticatedDocumentTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/document/terms': typeof AuthenticatedDocumentTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/_authenticated/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/_authenticated/document/terms': typeof AuthenticatedDocumentTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/document/privacy' | '/document/rules' | '/document/terms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/document/privacy' | '/document/rules' | '/document/terms'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/document/privacy'
    | '/_authenticated/document/rules'
    | '/_authenticated/document/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/privacy': {
      id: '/_authenticated/document/privacy'
      path: '/document/privacy'
      fullPath: '/document/privacy'
      preLoaderRoute: typeof AuthenticatedDocumentPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/rules': {
      id: '/_authenticated/document/rules'
      path: '/document/rules'
      fullPath: '/document/rules'
      preLoaderRoute: typeof AuthenticatedDocumentRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/terms': {
      id: '/_authenticated/document/terms'
      path: '/document/terms'
      fullPath: '/document/terms'
      preLoaderRoute: typeof AuthenticatedDocumentTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentPrivacyRoute: typeof AuthenticatedDocumentPrivacyRoute
  AuthenticatedDocumentRulesRoute: typeof AuthenticatedDocumentRulesRoute
  AuthenticatedDocumentTermsRoute: typeof AuthenticatedDocumentTermsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentPrivacyRoute: AuthenticatedDocumentPrivacyRoute,
  AuthenticatedDocumentRulesRoute: AuthenticatedDocumentRulesRoute,
  AuthenticatedDocumentTermsRoute: AuthenticatedDocumentTermsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
